### ISSUE TITLE
Possible to provide link to orig. size image from an entry?

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#100]

**Comment by steinmb** [comment]
I have created a custom view mode for image that link to the original file and uses a new custom scale to resize the with of the image to 800px in a regular view.
 
Character, Creative Work and Machine Vision Situation now render image with the new view mode.

**Comment by LindaKairus** [comment]
I think the 800px resize works. When I went through a number of images There were no images that were stretched at least to the degree that it would look very pixelated. So, I think it will be fine. If the resizing is smaller than 800px I am afraid that it could be too small, so I suggest we keep it like this and close the comment.
