### ISSUE TITLE
List of all entries authored by user on user account page

### ISSUE THREAD

**Issue by mareinna** [jilltxt/machinevision#101]
User account provided a list of entries (records authored) by user on the user account page. Example https://old.machine-vision.no/users/marianne (yes, you need to login). This was provided by a view that is not something we could migrate and we need to recreate.

## Suggested fix

* Recreate view
* View filter based on the user profile you visit. Example: https://machine-vision.no/user/marianne and https://machine-vision.no/user/admin vs https://machine-vision.no/user/steinmb

## How to review

* Visit your user profile and verify that records authored by you is listed and expose correct data.
* Visit someone else user account and verify that that users records are listed and expose correct data.

## Original report

>The option to see all entries made by a specific user has disappeared. It was really useful, especially when it could also be sorted or filtered by type of entry (work/situation/creator/etc). Remake/reinstate?

**Comment by steinmb** [comment]
Have started work on this and people could start reviewing and testing. I do not think we are don but it is a start. I think we can improve the original implementation we had in the old site. I am open for suggestions.

**Comment by jilltxt** [comment]
This looks great! Except that when you're in that view the name of the person who made the entries is missing, which is a bit confusing. Here is a screenshot. But you get to the lists easily from the list of people. I like it. 
<img width="995" alt="Screen Shot 2020-09-04 at 15 01 19" src="https://user-images.githubusercontent.com/44365847/92242187-b6b99000-eebf-11ea-859a-e32cde3154c7.png">

**Comment by steinmb** [comment]
@jilltxt I think I forgot to mention, I have added 3 new fields in the user profile. if you fill them out it is used as a header of the page: https://machine-vision.no/user/admin something like that. Was that what you referring to?

**Comment by jilltxt** [comment]
Looks great now!
