### ISSUE TITLE
Improve the ability to create entities that do not exist

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#102]
Back in Drupal 7 we could create end inline edit the newly created entity while referencing it. 

In Drupal 9 we have a light version of this. It allow us to reference entities (verbs, characters) that do not exist. It currently does not allow us to fill out (inline forms) details but it create the non exiting when you save and link to it allow you to edit it. It is a bit convoluted but it works. Have a look at this.

[Screen Recording 2020-07-15 at 17.38.46.mp4.zip](https://github.com/jilltxt/machinevision/files/4926411/Screen.Recording.2020-07-15.at.17.38.46.mp4.zip)

## Improvements

Test out similar functionality in Drupal 9 with and without `paragraphs` and if stable implement it. If not we wait and/or jump patch the problem.

## Blocker
For a improved inline editing I am holding back, waiting for this to get ready:
 https://www.drupal.org/project/inline_entity_form/issues/3121071
and a stable release.

## How to test

TBD

**Comment by jilltxt** [comment]
I think this can be closed now @steinmb?

**Comment by steinmb** [comment]
Yes. Closing
