### ISSUE TITLE
Allow us to enter only year in creative work year form

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#103]
Drupal 7 had no core date or datetime support instead it was provided by a third part module (Date). It had functionality to change the date form validation. Behind the scene it still registered a date, `01-01`. In Drupal 8 this type of data is supported by core it self. What we not get is this kind of flexibility.

As is we have to enter a date, any date will do then we do not expose/use it. This is not ideal.

## Drupal 7 year storage

```
.....
+------+------------------+
| ID   | field_year_value |
+------+------------------+
|   71 | 2018-01-01       |
|   73 | 1978-01-01       |
|   75 | 2014-01-01       |
|   80 | 2015-01-01       |
|   82 | 1909-01-01       |
|   86 | 2018-01-01       |
|   90 | 2019-01-01       |
|   92 | 2017-01-01       |
|   94 | 2019-01-01       |
|   96 | 2012-01-01       |
|  102 | 2013-01-01       |
|  104 | 1999-01-01       |
|  106 | 1971-01-01       |
|  108 | 2014-01-01       |
....

## Suggested fix

TBD

**Comment by jilltxt** [comment]
I think we agreed just to enter dates as 2020-01-01 and not worry about this?

**Comment by steinmb** [comment]
I think so. But my understanding was, this was a workaround until we could address it properly. I personally think we should but I am totally OK by leaving as it is.

**Comment by jilltxt** [comment]
Oh right! If it's not very hard, then certainly, it would be great to be able to just type in the year, not a full date. This would also be useful in the ELMCIP KB.

**Comment by jilltxt** [comment]
Closing this as we aren't entering new works any more.
