### ISSUE TITLE
Something wrong with adding Situations to a Creative Work?

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#107]
I can't manage to Add a Situation to a Creative work page. It says the node doesn't exist, although I definitely have created the Situation node. Taking a closer look, I see that it doesn't use the full title of the Situation, only the bit in parentheses. Are the parentheses causing a problem? I tried to add both a Situation I actually made for Brave New World, and when that didn't work, I tried a situation from Neuromancer, and both failed. Also, there is no autocomplete in this field.

Has anyone else successfully added a situation? I feel like I've done it before after the upgrade but can't remember exactly when the upgrade happened.

<img width="746" alt="Screen Shot 2020-09-04 at 15 29 21" src="https://user-images.githubusercontent.com/44365847/92244866-cd61e600-eec3-11ea-9373-1a137b54ffce.png">
<img width="719" alt="Screen Shot 2020-09-04 at 15 27 31" src="https://user-images.githubusercontent.com/44365847/92244868-ce931300-eec3-11ea-910a-2182be29159b.png">

**Comment by steinmb** [comment]
I'll have a look

**Comment by steinmb** [comment]
Sorry. Unable to reproduce. I notice from your screenshot that the link text is lacking the node id. The `(id)` is included by the node form autocomplete widget telling you that it found a match, you selected it and what the id it is in case you have multiple with identical title.

## Example from https://machine-vision.no/node/add/work

![Screenshot 2020-09-07 at 11 55 42](https://user-images.githubusercontent.com/683617/92375583-98db6d80-f101-11ea-9177-a9e21b2a345e.png)

**Comment by jilltxt** [comment]
This now works, I don't know why it didn't last time. Closing the issue.
