### ISSUE TITLE
Create data export views for data sprint

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#110]
Here are the data exports we would like to start with. Probably more would be good too, but at this shows main focus. I included the research questions so it's clearer what the point is. 

We mostly want datasets with links/edges between two kinds of node. We made a table below, but perhaps an easier way of putting it is:

- [ ] Creative works with Year, Publication Type, Technologies Used, Technologies Referenced, Topics, Sentiments, Characters, Situations. Jill's attempt (but this has validation errors): [https://machine-vision.no/admin/structure/views/view/creative_works/edit/data_export_1](https://machine-vision.no/admin/structure/views/view/creative_works/edit/data_export_1)
- [ ] Issue #111 - Character and verbs, Entities and verbs, Technologies and verbs
- [ ] Situation with Title, Aesthetics, Colours. 
- [ ] Situation with the Publication Type, Sentiment, Topic - but those are all in the Creative work the Situation belongs to so a bit trickier?
- [ ] Character with all its attributes
- [ ] Creator (Person) with nationality AND characters in situations in works that the creator has created

Node type 1 | Node type 2 | Research questions
-- | -- | --
Character (in situations) | Verbs | What are machines doing? What are humans doing? What are the entities doing? What verbs are connected to specific technologies, e.g. AI or holograms? What are artists doing, how are they using machine vision? (use entities + verbs) Maybe collapse all the (human) characters (as “humans” or “fictional”) and view them alongside the entities and the technologies? How do we conflate the characters so we don’t have a gazillion different nodes but can view things more holistically. The human-machine assemblage – make a beautiful visualization to put on the wall and in our paper – showing the complex interactions between humans and machines…
Situation-->Entities | Verbs | as above
Situation-->Technologies  _We need to know the Genre, Sentiment, Topic of each situation as well (in columns in same export) but they are located in the Creative Work, not the Situation – how can we get this in?_ | Verbs | as above
Character | All the attributes (species, sexuality etc) | What kind of characters are represented in our dataset? What kinds of characters are visible in stories about machine vision? Is it different in works of  Combine this with tech + verbs: Do characters with tech integrated use different verbs than technologies alone do?
Creator/author (+ nationality) | Characters in works created by that author (include character attributes) | Are authors/creators in certain countries more likely to portray different kind of character? E.g. are Japanese authors more likely to portray women or robot characters?
Year of publication of work | Attributes of characters in the work | Are characters more diverse over time? Are characters more machinic over time?
Attributes of characters (species, race, sexuality etc) | Verbs used by those characters (in situations) | Bias
Nationality of creator | Technologies RepresentedTechnologies RepresentedTopicsSentiment | Do different parts of the world tend to explore different technologies? Different topics? Different sentiments?
Situation | Verbs in the situation | What verbs occur together in the same situation?
Work (with all the attributes) | Technologies Referenced | Which technologies tend to be used or referenced in games vs artworks, or in movies about cities vs movies about family?
Topic (in the Creative Work) | Technologies (in Creative Work) | Which technologies are connected to certain topics? E.g. hacking? Sex? Labour?
Sentiments | Technologies | Are different emotions connected to different works??
  |   |

**Comment by steinmb** [comment]
https://machine-vision.no/work now works though it create a huge data set. I did a full export on my local machine and it took about 25 minutes. I ended up with a CSV-files with 141 157 lines. Did not test this one the production servers but I guess it will take just as long. I have set a hard limit in production for 1000 lines.

I have a example on a full export at the [UiB sharipointthingy](https://universityofbergen.sharepoint.com/:f:/r/sites/MachineVision/Shared%20Documents/Database/Datasprint%20Sept%202020/Data%20exports?csf=1&web=1&e=nyh0ZI)

## Example. First record of the export

| Title                | Year | Type of work          | Pub Type ID | Science fiction? | Characters | Sentiment | Sentiment ID | Situation machine vision is used in          | Situation ID | Technologies referenced | Tech ref ID | Technologies used  | Tech used ID | Topics  | Topics ID | Year | ID   | Characters ID |
| -------------------- | ---- | --------------------- | ----------- | ---------------- | ---------- | --------- | ------------ | -------------------------------------------- | ------------ | ----------------------- | ----------- | ------------------ | ------------ | ------- | --------- | ---- | ---- | ------------- |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 138         | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Flawed    | 208          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Camera             | 206          | Playful | 170       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | AI      | 168       | 2018 | 1658 |               |
| Memoirs of the Blind | 2018 | Installation art, Art | 2           | Off              |            | Fun       | 212          | Memoirs of the Blind (capturing eyes closed) | 1659         |                         |             | Facial recognition | 7            | Playful | 170       | 2018 | 1658 |               |
|                      |

```

```
