### ISSUE TITLE
Views data export - Character and verbs, Entities and verbs, Technologies and verbs

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#111]
Split out from issue #110 Have a sneaking feeling we will go forth a back a few times.

## Data exports created

* https://machine-vision.no/character
* TBD

## Data structure

Node type 1 | Node type 2 | Research questions
-- | -- | --
Character (in situations) | Verbs | What are machines doing? What are humans doing? What are the entities doing? What verbs are connected to specific technologies, e.g. AI or holograms? What are artists doing, how are they using machine vision? (use entities + verbs) Maybe collapse all the (human) characters (as “humans” or “fictional”) and view them alongside the entities and the technologies? How do we conflate the characters so we don’t have a gazillion different nodes but can view things more holistically. The human-machine assemblage – make a beautiful visualization to put on the wall and in our paper – showing the complex interactions between humans and machines…
Situation-->Entities | Verbs | as above
Situation-->Technologies  _We need to know the Genre, Sentiment, Topic of each situation as well (in columns in same export) but they are located in the Creative Work, not the Situation – how can we get this in?_ | Verbs | as above
Character | All the attributes (species, sexuality etc) | What kind of characters are represented in our dataset? What kinds of characters are visible in stories about machine vision? Is it different in works of  Combine this with tech + verbs: Do characters with tech integrated use different verbs than technologies alone do?
  |   |

**Comment by jilltxt** [comment]
Thanks! The characters export looks great! Except it **needs unique IDs for each of the characters** as well, so we can make the edge tables.

<img width="727" alt="Screen Shot 2020-09-25 at 08 04 32" src="https://user-images.githubusercontent.com/44365847/94232236-dfa0d400-ff05-11ea-9006-b3e622c0588d.png">

We need to be able to make edge tables that look like this, just with the ID of the source node (in this case characters) and of the target node (in this case probably verbs)

<img width="147" alt="Screen Shot 2020-09-25 at 08 06 34" src="https://user-images.githubusercontent.com/44365847/94232348-14149000-ff06-11ea-838f-608e8babbf79.png">

**Comment by jilltxt** [comment]
This is no longer a problem.
