### ISSUE TITLE
Fix data in the database

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#112]
Exporting and visualising the data shows us some gaps or inconsistencies in the way we've entered stuff into the database. Let's list issues here so we can fix them after the Datasprint week.

- [ ] Many works do not have Science fiction on or off - go through them and fix.
- [x] The action (verb) "Playing" has two different unique IDs - replace 624 with 629
- [ ] A number of characters do not have any actions - find these and add (or are these characters who are not in any specific situations?
- [x] Misspellings: watching spelt as "waching"

**Comment by KurdinJ** [comment]
@jilltxt, the one with Science fiction on or off, is this a something I can fix? I mean would I now if the work is Science fiction or not? I would probably know with the movies, but not sure for the rest.

**Comment by ragsol** [comment]
> 
> 
> @jilltxt, the one with Science fiction on or off, is this a something I can fix? I mean would I now if the work is Science fiction or not? I would probably know with the movies, but not sure for the rest.

I think we should all do the sci-fi on our own works. Seems to much to ask of Kurdin to know all the works in the database =)

**Comment by jilltxt** [comment]
That sounds reasonable, yes!

**Comment by jilltxt** [comment]
Closing this as I don't think it's still needed given the data export we're doing.
