### ISSUE TITLE
Create view for each taxonomy item

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#113]
We have some duplicates in the [Verbs taxonomy](https://machine-vision.no/admin/structure/taxonomy/manage/verbs/overview?page=1), and some misspellings. It is difficult to fix these now because there is no easy way to view all nodes in which each Verb occurs. Perhaps this is because they are in paragraphs not in nodes? 

For instance, using the data export for Characters + Verbs I have gone back to the database and changed all US spellings of "Analyzing" to the UK spelling "Analysing", but I am afraid to delete the "Analysing" from the taxonomy list in case there are Technologies or Entities that use this spelling of the verb. I see there are two nodes called "Defying" but I don't want to delete one until I have changed all the instances using one of those to the other. 

<img width="953" alt="Screen Shot 2020-09-30 at 17 01 04" src="https://user-images.githubusercontent.com/44365847/94703345-05cbd700-033f-11eb-9ef1-4b56cf8c6bc3.png">

**Comment by steinmb** [comment]
I will work on this later today

**Comment by steinmb** [comment]
It is a little silly but I might do the job. Uses the term id as a contextual filter when you select a term. Also included a filter that might speed things up.

* https://machine-vision.no/data/situations/terms
* Added to https://machine-vision.no/data_exports

Depending on how many we need to clean up. Do we need a option to merge terms in some way?

commit f6b2a7a2ecab52dddd836c0b7fdf92f2966f2590 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Oct 26 20:14:37 2020 +0100

    Issue 113 Views tool list Situations and terms

    Used to track down duplication and misspelling

**Comment by steinmb** [comment]
Related to issue #91

**Comment by jilltxt** [comment]
Don't need this after all as data can be exported so verbs spelled the same are the same.
