### ISSUE TITLE
Setup Github repository for data visualisations and data files

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#114]
We need secure and long-term storage of data exports, Gephi files and visualisations when we reach final versions. It probably makes sense to store data on Github and then put the data that is directly used in publications in research data storage, for instance in [UiB's section of Dataverse](https://dataverse.no/dataverse/uib), or in [NSD's data storage](https://nsd.no/arkivering/slik_arkiverer_du.html). Github seems like a sensible place for archiving data before it goes into long-term storage. 

- [x] Jill creates Organisation account on Github
- [x] Move this repository to new account
- [ ] Create separate project on new account for data exports and visualisations
- [ ] Update our Data Management Plan to describe process ([PDF](https://universityofbergen.sharepoint.com/sites/MachineVision/Shared%20Documents/Research/Data%20Management/Machine%20Vision%20Data%20Management%20Plan%20-%20NSD%20Template.pdf) / [Editable version at NSD](https://dmp.nsd.no/plan/ac120002-673b-1b06-8167-5af41e1700d4))

**Comment by steinmb** [comment]
This also allow us to move repos to the org. account. Currently living in smbjorklund org. account:

* github.com/smbjorklund/machinevision_config.git
* github.com/smbjorklund/elmcip_person
* github.com/smbjorklund/machine-vision-theme

This repo `jilltxt/machinevision` is no longer in use by Drupal and perhaps we should move all issues and other stuff to machinevision_config.git - that is the new site repo.

**Comment by steinmb** [comment]
Just created another that we need to remember to move:
* https://github.com/smbjorklund/machinevision_setup

**Comment by jilltxt** [comment]
I created the organisation account and moved this there (sorry it took so long). I think you moved a couple of things over there too, @steinmb?

**Comment by steinmb** [comment]
That is correct. I have moved two repos. but I also need to update the configs that our production system is built from. Example, our current theme. 

commit MachineVisionUiB/machinevision_config@ed91f59bf51c11afef8548b627785280cb90a1f3 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Feb 11 15:23:44 2021 +0100

    Move Machinevision theme to org. repos


commit MachineVisionUiB/machine-vision-theme@76569b52714c4399831d5cc159d03f888229ea17 (HEAD -> 8.x-dev, origin/HEAD, origin/8.x-dev)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Feb 11 12:37:38 2021 +0100

    Move theme ownership to Machine vision org. account
