### ISSUE TITLE
Check all publication types

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#115]
Go through _all_ publication types and check that anything tagged as a sub-genre (e.g. movies, novels, installation art) is ALSO tagged as Narrative or Art. 

NARRATIVE: 

- [x] [Movies](https://machine-vision.no/creative-work-publication-type/movie)
- [x] [Novels](https://machine-vision.no/creative-work-publication-type/novel)
- [x] [Short stories](https://machine-vision.no/creative-work-publication-type/short-story)
- [x] [TV series or episode](https://machine-vision.no/creative-work-publication-type/tv-series-or-episode)
- [x] [Fan fiction](https://machine-vision.no/creative-work-publication-type/fan-fiction)
- [x] [Creepypasta](https://machine-vision.no/creative-work-publication-type/creepypasta)
- [x] [Comic](https://machine-vision.no/creative-work-publication-type/comic)
- [x] [Electronic literature](https://machine-vision.no/creative-work-publication-type/electronic-literature)

ART: 

- [x] [Video art](https://machine-vision.no/creative-work-publication-type/video-art)
- [x] [Performance art](https://machine-vision.no/creative-work-publication-type/performance-art)
- [x] [Installation art](https://machine-vision.no/creative-work-publication-type/installation-art)
- [x] [Photograph/print/painting](https://machine-vision.no/creative-work-publication-type/photographprintpainting)
- [x] [Online art](https://machine-vision.no/creative-work-publication-type/online-art)

The other genres can be left alone. 
GAMES has no subgenres

Music videos, Advertisements, Online videos, Board games and Other are their own genres (in the database, anyway), and should not be given a top-level genre.

**Comment by KurdinJ** [comment]
Why can I not hook off?

**Comment by jilltxt** [comment]
> Why can I not hook off?

In the collaborators settings for this repository it says you haven’t responded to the invitation yet - can you check your account and see if there is an invite to accept?

**Comment by KurdinJ** [comment]
Could not find any invitation. But I clicked on the link for invitation in the e-mail account and I get this error: 

“Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.”

**Comment by jilltxt** [comment]
I just deleted the first one and sent a new one - maybe it will show up?

**Comment by KurdinJ** [comment]
It worked just fine this time.

**Comment by KurdinJ** [comment]
@jilltxt, done.
