### ISSUE TITLE
Change all uses of "Analyzing" and "analysing" to Analysing, then delete 

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#116]
We are standardising to British spellings of verbs, so -sing not -zing. We had three different spellings of analysing in the database, and each had a unique node ID so this messes up the visualisations. Unfortunately, Jill deleted the verb "analysing" (without a capital A) and so we lost some data.

Please go through all the following situations with instances of Analyzing (525) and Analyzed (753) with a Z, and change them to "Analysing" (364)  (capital A and -sing/-sed). 

- [x] B.I.T. Plane (Drone investigating) | Analyzed
- [x] Come Out To LA (Robinator scans Tom) | Analyzed
- [x] Drawing Operations (Robot collaborates on painting) | Analyzed
- [x] Terminator 2 (Terminator learns to smile) | Analyzed
- [x] >observer_ (Augmented visions) | Analyzing
- [x] Death Stranding (Odradek scanner) | Analyzing
- [x] Drawing Operations (Robot collaborates on painting) | Analyzing
- [x] Goodnight, Melancholy (Nocko meets Lindy) | Analyzing
- [x] Halo: Combat Evolved (AI hologram) | Analyzing
- [x] Hell No (Filtering) | Analyzing
- [x] Horizon Zero Dawn (Focus technology) | Analyzing
- [x] Nemesis (Scanning emotions) | Analyzing
- [x] Spiderman: Far from Home (Augmented reality) | Analyzing
- [x] Tendar (Emotion recognition) | Analyzing
- [x] Terminator 2 (Terminator scans bikers) | Analyzing

The second group of situations used to have "analysing" in them but the verb disappeared completely when Jill deleted it (oops). Please go through the following list to add "Analysing" (364) in again. All these situations have a **Technology** doing the Analysing, and in many situations it's multiple technologies.

- [x] (Rick and Morty) Rick scans twig for clues | Motion tracking
- [x] (Rick and Morty) Rick scans twig for clues | Object recognition
- [x] 79530 Self Portraits (GAN transforming errors) | Machine learning
- [x] A Hipster Bar (hipster recognition) | Object recognition
- [x] AI Generated Nude Portraits | Machine learning
- [x] AI helping the Simpsons family | AI (General Purpose Artificial Intelligence)
- [x] Asunder (environmental managing) | Machine learning
- [x] Belief Systems (Shopping for kettle with face) | Emotion recognition
- [x] Belief Systems (Shopping for kettle with face) | Camera
- [x] Cheese (Women smiling) | Emotion recognition
- [x] China Mountain Zhang (Building recognises faces) | Facial recognition
- [x] Drone Selfies (Drones) | Drones (UAV)
- [x] Fall of the House of Usher (Machine reinterpreting visuals) | Machine learning
- [x] Gluttonous Snake (Playing by smiling) | Emotion recognition
- [x] Gluttonous Snake (Playing by smiling) | Webcams
- [x] How to be More or Less Human (Undressing) | Object recognition
- [x] Johnny Mnemonic (Body scan in Passport Control) | Body scans
- [x] Johnny Mnemonic (Body scan in Passport Control) | Camera
- [x] Narciss (Self-analysing Machine) | Camera
- [x] Narciss (Self-analysing Machine) | Machine learning
- [x] Narciss (Self-analysing Machine) | Object recognition
- [x] October Faction (Detecting Hostile Aliens) | Cameraphone
- [x] October Faction (Detecting Hostile Aliens) | Object recognition
- [x] October Faction (Detecting Hostile Aliens) | Non-Visible Spectrum
- [x] Pattern Recogntion (Security scanning for lying/blushing) | Non-Visible Spectrum
- [x] Postcard from Google Earth (Satellite images) | Satellite images
- [x] Postcard from Google Earth (Satellite images) | Machine learning
- [x] pplkpr (Body scans) | Body scans
- [x] pplkpr (Body scans) | Machine learning
- [x] Probably Chelsea (creating DNA 3D facial prints) | Image generation
- [x] Probably Chelsea (creating DNA 3D facial prints) | Machine learning
- [x] RASA-BOX (machine mirroring you) | Camera
- [x] RASA-BOX (machine mirroring you) | Machine learning
- [x] Robotika (Robot caring for baby) | AI (General Purpose Artificial Intelligence)
- [x] See you (Machine learning face singing) | Machine learning
- [x] Self-Contained (Artist viewed by machine) | Machine learning
- [x] Significant Other (comparing emotions) | Emotion recognition
- [x] Significant Other (comparing emotions) | Machine learning
- [x] Terminator 2 (Terminator learns to smile) | Emotion recognition
- [x] Terminator 2 (Terminator learns to smile) | Augmented reality
- [x] Us+ (Emotion recognition) | Webcams
- [x] Us+ (Emotion recognition) | Emotion recognition

When this is done, let Jill know so she can delete the verbs from the taxonomy.

**Comment by KurdinJ** [comment]
@jilltxt, done!
