### ISSUE TITLE
Fix Situations with incorrect use of brackets

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#117]
Situation titles should be in the following format:

_Title of work (2-4 word description of situation)_

Please rename these situations, which have the title of the work in parenthesis instead of the description of the situation. So (Better Off Ted) Failing dark skin needs to be changed to Better Off Ted (Failing dark skin). Here are all the mis-named Situations:

- [x] (Better Off Ted) Failing dark skin
- [x] (Deep Dark Fears) Reflection recording Fran
- [x] (Public Waiters) Recognizing colors
- [x] (Rick and Morty) Rick detecs intruder
- [x] (Rick and Morty) Rick scans twig for clues
- [x] (Rick and Morty) Scanning feces samples
- [x] (Rick and Morty) Summer using dating app

**Comment by ragsol** [comment]
Also goes for the order of the words:

- [x] Holograms (The Under Presents) should be The Under Presents (Holograms)
- [x] Drone assasination (Drones Don't Kill People) 
- [x] Drone surveillance (Drones Don't Kill People)
- [x] Surveillance man watching child (Excellent) 

and for those without parenthesis:

- [x] Satellite Images
- [x] Coronavirus drone
- [x] The Coded Gaze: Unmasking Algorithmic Bias
- [x] Homer scans people 
- [x] AI helping the Simpsons family
- [x] Robots trying to kill the Simpsons family
- [x] Zapp Brannigan spies on Leela

Also, there's a mysterious Situation called Drones (Drones) made by LH, but there's no work called Drones... 
- [x] Figure out where this is and rename it or delete it?

and there's a Situation called Selfdriving car sees a deer that belongs to a Work called Earthware (driverless car seeing a deer for the first time 2)
- [x] Tidy the titles

**Comment by jilltxt** [comment]
@KurdinJ - do you have time to go through these?

**Comment by KurdinJ** [comment]
Yes @jilltxt I do.

**Comment by KurdinJ** [comment]
@jilltxt, those without parenthesis "Satellite Images, etc", aren't they supposed to refer to a work? Work title first and then situation title in parentheses? or should I just put them in parenthesis without adding work title?
