### ISSUE TITLE
Fix Characters with incorrect names

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#118]
If a character doesn't have a name, we describe them with something + brackets of where they're from, e.g. Audience (Man with a Movie Camera). Some characters are missing this, e.g. Unnamed intern / Unnamed woman, and probably more. Just go to https://machine-vision.no/admin/content, choose "content type: character", click "Title" to sort alphabetically, and look through the list, fixing those who have no names and no brackets.

**Comment by KurdinJ** [comment]
@ragsol how to find out what these characters "are"? I tried to fix it, but could not figure out? for example this one: https://machine-vision.no/node/1149/edit what should I name the women?

**Comment by jilltxt** [comment]
@KurdinJ Search the database for the name of the character, e.g. for "unknown woman" and look for Creative work entries to find the one where the character is listed. I fixed the one you linked to, which was in "The Webcam Project".

**Comment by KurdinJ** [comment]
@jilltxt, ok. So not just describe them, we should also write the creative work name in parentheses together with the character name, like Unnamed woman (The Webcam Project)?

**Comment by jilltxt** [comment]
Yes!!
