### ISSUE TITLE
Make new user category with less privileges?

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#119]
We are hiring ten research assistants. Could we enable a contributor level account for them where they cannot edit other peoples' entries? Right now there is nothing between Administrator and Authenticated User, because we thought we'd only have the project participants, but it'd be great to add a level now...

**Comment by steinmb** [comment]
Sure we can. This type of users should only be allowed to create new and edit own records?

**Comment by jilltxt** [comment]
Exactly!

**Comment by steinmb** [comment]
Created a user group named `All user content` - that is allow to change/edit/remove all user generated content. Core machine vision persons belong to this group. The generic user group, `authenticated user` now only give everyone permission to work with own content.

**Comment by jilltxt** [comment]
That sounds perfect. I took a look at the list of users and it looks good! Thank you!
