### ISSUE TITLE
Make a view that shows all Creative Works that are missing Situations

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#120]
@steinmb - are you able to make us this view? We need to make sure we have situations for all the works.

**Comment by steinmb** [comment]
I will work on this later today

**Comment by steinmb** [comment]
* Added to overview page, https://machine-vision.no/data_exports
* View: https://machine-vision.no/data/creative-work-with-no-situation

commit 0302f0affe4ae4cd1045c404201a739c6392304e (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Oct 26 16:38:50 2020 +0100

    Issue 120 Create work with no situation view

    Make it easier to find these type of creative work

**Comment by jilltxt** [comment]
This is great, thanks!!
