### ISSUE TITLE
Fix Generic entities

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#121]
Name	Operations
Aliens
Animals
Assimilation City
Bikers
Building
Casino the Rapper (deleted)
Chung`s archive
Community
Corporation
Creator
Crowd
Deer
Environment
Face
Fans
Feces
Girls on screen
Glad Girls
Government
Humans
Image
Images
Infant
Internet
Military
Movie
Necklace
NGO
Object
Paper (band)
People
People approaching house
Person recording concert
Plastic surgeons
Police
Population
Robinator
Robot
Robots
Shopper
Silicon Valley
Smiling guy
Standing Rock Ground
Styled people
Target
The Creator
The Creator (Janelle)
The Flemming Family
The Police Force
The Workers
Tom
Unspecified individuals
User
Woman entering car
Women

**Comment by ragsol** [comment]
What we have in the overview now:
Corporation, Creator, Government, Image, Object, User

**Comment by jilltxt** [comment]
Keep these entities:

Corporation
Creator
Government
Image
Object
User
Law Enforcement
Military
Humans in general
Environment

- [x] Change description in database
- [x] Change "Humans" (entity) to "Humans in general" in the database
- [ ] Rename Police as Law Enforcement
- [ ] Find list of Situations using "Humans" as CHARACTER and change all to ENTITY

Check that none of these are still used as entities - change to characters, delete etc.
- [x] Aliens NO 
- [x] Animals NO
- [x] Assimilation City NO
- [x] Bikers NO
- [x] Building NO
- [x] Casino the Rapper (deleted)
- [x] Chung`s archive NO
- [x] Community NO
- [x] Corporation KEEP
- [x] Creator KEEP
- [x] Crowd NO --> Humans
- [x] Deer NO
- [x] Environment KEEP
- [x] Face NO 
- [x] Fans NO 
- [x] Feces NO --> Object
- [x] Girls on screen NO
- [x] Glad Girls NO
- [x] Government
- [x] Humans YES
- [x] Image KEEP
- [ ] Images Change to Image
- [x] Infant
- [x] Internet
- [x] Military KEEP
- [x] Movie
- [x] Necklace
- [x] NGO
- [x] Object KEEP
- [x] Paper (band)
- [x] People
- [ ] People approaching house CHANGE TO HUMANS IN GENERAL
- [ ] Person recording concert CHANGE TO HUMANS IN GENERAL
- [ ] Plastic surgeons CHANGE TO HUMANS IN GENERAL
- [ ] Police KEEP
- [ ] Population CHANGE TO HUMANS
- [ ] Robinator
- [ ] Robot
- [ ] Robots
- [ ] Shopper
- [ ] Silicon Valley
- [ ] Smiling guy
- [ ] Standing Rock Ground
- [ ] Styled people
- [ ] Target KEEP
- [ ] The Creator CHANGE TO CREATOR
- [ ] The Creator (Janelle) (CHANGE TO CREATOR)
- [ ] The Flemming Family
- [ ] The Police Force
- [ ] The Workers
- [ ] Tom
- [ ] Unspecified individuals
- [ ] User KEEP
- [ ] Woman entering car
- [ ] Women

**Comment by jilltxt** [comment]
I have deleted all the un-used Entities, updated the description, and it's now a controlled vocabulary, so we cannot add new Entities when making entries. 

I deleted Environment too hastily, so need to look through an old export to add back any deleted uses. See #134
