### ISSUE TITLE
Override node forms

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#123]
In the original Drupal 7 version of the site we had a few overrides of the node form. Especially when we use radio button widgets on large data sets.

In Drupal 9 we use another admin theme and the way you implement these are a little different.

## Example on long lists

![Screenshot 2020-10-27 at 09 38 05](https://user-images.githubusercontent.com/683617/97312322-a8577700-1865-11eb-9205-b4986c336ce2.png)

**Comment by steinmb** [comment]
Created custom module - https://github.com/smbjorklund/machinevision_setup

commit 884e0b2db6a744985e40a80be2665bd9827cea60
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 16 18:39:47 2020 +0100

    Add machinevision_setup to composer.json

commit 304542999c20588aa6910ddd81a4fdf3e9720865
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Nov 2 14:19:50 2020 +0100

    New Machine vision module


![Screenshot_2020-11-16 Create Creative Work Machine Vision](https://user-images.githubusercontent.com/683617/99296544-390eea80-2847-11eb-812b-7f2dab6fc29f.png)

**Comment by jilltxt** [comment]
I absolutely love having the items in two columns - it makes it much easier to get an overview!
