### ISSUE TITLE
Check all new entries by research assistants

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#128]

**Comment by jilltxt** [comment]
We need to go through all the works entered by the scifi team. 

## CREATIVE WORKS TO CHECK
- [ ] [A Memory Called Empire](https://machine-vision.no/creative-work/memory-called-empire)

[... som duften av en drøm...](https://machine-vision.no/creative-work/som-duften-av-en-drom)
- [ ] Delete [Postal drones situation](https://machine-vision.no/machine-vision-situation/som-duften-av-en-drom-postal-drones) because no description of visual tech
- [ ] Check - too many verbs
- [ ] Too many topics?
- [ ] Check ALL the situations...

**Comment by ragsol** [comment]
Check if some of the situations in this work is the same - seems like a lot of holograms might be doing the same thing: https://machine-vision.no/creative-work/star-wars-episode-7-8-9

**Comment by ragsol** [comment]
We check that everything's filled out, that there's not too many topics/sentiments/situations/verbs etc. Also, check if all characters are okay, that they are tied to a situation and all situations to a work. In total, there's 64 works and 233 (!) situations. I suggest the following division, to make it fairly equal (based on the numbers, not content):

Jill (14, 61)

- [x] Ida: https://machine-vision.no/user/ida, 3 works and 32 situations
- [x] **Sunniva**: https://machine-vision.no/user/sunniva, 6 works and 14 situations (~~How to Sell Drugs Online (Fast)~~, ~~Osmosis~~, ~~3%~~, ~~Órbita~~, ~~Spider-Man: Into the Spider-Verse~~, ~~Mono no Aware~~)
- [x] Amanda: https://machine-vision.no/user/amanda, 5 works and 15 situations (~~Cosmodrama~~, ~~Best Friend~~, ~~Behind our Irises~~, ~~Yat Madit~~, ~~Incredibles 2~~

Ragnhild (27, 70)
- [x] Ainsley: https://machine-vision.no/user/ainsley, 11 works and 37 situations
- [x] Milad: https://machine-vision.no/user/milad, 6 works and 16 situations
- [x] Edward: https://machine-vision.no/user/edward, 10 works and 17 situations

Marianne (12, 47)
- [x] Milosz: https://machine-vision.no/user/milosz, 7 works and 37 situations
- [x] Cecilie: https://machine-vision.no/user/cecilie, 5 works and 10 situations

Linda (11, 55)
- [x] Tijana: https://machine-vision.no/user/tijana, 5 works and 33 situations
- [x] Andrés: https://machine-vision.no/user/andres, 2 works and 7 situations
- [x] Martin: https://machine-vision.no/user/martin, 4 works and 16 situations


Side note: Is "[Anne](https://machine-vision.no/user/anne)" Anne K? (missing situation). Also, some things are filed under "[admin](https://machine-vision.no/user/admin)".

**Comment by jilltxt** [comment]
Thank you, Ragnhild! This is great. Anne K is Anne Karhio, she did some work on the project in 2018 - I’ll ask her to add the situation. I’ll take the first  bunch!

**Comment by ragsol** [comment]
I waited a couple of days in case anyone else wanted to pick, and then I took the second one because it has a lot of films I've already watched.

**Comment by ragsol** [comment]
I'll leave it here because I couldn't find anywhere else:

These works need an extra pair of eyes. I've posted what needs to be checked/discussed in the notes section. Feel free to edit directly and do "two or more".

- [ ] https://machine-vision.no/creative-work/dr-who-series-7
- [ ] https://machine-vision.no/creative-work/circle-0
- [ ] https://machine-vision.no/creative-work/black-mirror

**Comment by ragsol** [comment]
In fact, we should just go through the "Needs discussion" list:

- [ ] [Needs discussion list](https://machine-vision.no/record-status/needs-discussion)
