### ISSUE TITLE
Make database searchable by country Creator is affiliated with

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#130]
We should have a view showing countries and which Creators are affiliated with them.

I added Country to the Creative Work as I think it is important that visitors to the database can see it there. It is not currently clickable. Can it be made clickable? Or is there another way of displaying Creative Works by country?

<img width="716" alt="Screen Shot 2020-11-30 at 11 28 33" src="https://user-images.githubusercontent.com/44365847/100598686-5dff6500-32ff-11eb-85fb-b923ac03f2e7.png">

**Comment by steinmb** [comment]
There are multiple way of doing this. Just to get the ball rolling I have pushed a change to production in just to have something we can look at and discuss. https://github.com/MachineVisionUiB/machinevision_config/commit/881aef0a5965bdc987d663505227322feaf6c77c

* https://machine-vision.no/work - There is now a extra exposed filter allowing everyone to filter on country.
* Linking from creative work should link to a page automagically filtering on selected country. I think I have to write a custom field formatter linking to `/work/country/country_id` to allow us to pull this off. Until that, I went ahead an created a custom page listing work based on a filter like this. Example: https://machine-vision.no/work/country/NO links all Norwegian work.

**Comment by jilltxt** [comment]
This looks great! Searching by country is useful, but would it be possible to only show countries with data (I mean, with entries from that country) in the list? The list is sooo long!

I like the way the custom page you made looks, that's a great way of displaying it.
