### ISSUE TITLE
Multi-column layout child elements hidden in Firefox editing nodes

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#132]
There seems to be a weird bug when making a "creative work" in two places.
![bug](https://user-images.githubusercontent.com/49433622/100581313-d4906880-32e7-11eb-9ec5-895d7a367b98.png)
![bug2](https://user-images.githubusercontent.com/49433622/100581316-d65a2c00-32e7-11eb-8ece-b54a7253f0fe.png)

Both in "Topics" and "Sentiment" we are not able to check of the box in the top right "corner" of the boxes.

**Comment by jilltxt** [comment]
That's a weird bug! It doesn't happen for me. I'm using Safari on a Mac. What browser are you using, @LinnHeidi?

**Comment by steinmb** [comment]
Might be related to issue #123 - Last time we did something to the check boxes. And yes, as Jill mention, It would help if you told us what browser and version you are seeing this in.

**Comment by jilltxt** [comment]
@LinnHeidi will be working Monday and Thursday mornings for now so will no doubt answer on Thursday :)

**Comment by steinmb** [comment]
Np. I manged to re-produce it in Firefox 83.0 - A peekaboo error. Show up when I resize the node edit form. Looks like this:

## Peekaboo!

![peekaboo](https://user-images.githubusercontent.com/683617/100751690-ed804300-33e7-11eb-91f8-8b6fb449a23e.gif)

**Comment by LinnHeidi** [comment]
Ah, yeah! Thats what happens! I like the name of this error though! :D Thank you for figuring it out ! I will close thise!

**Comment by steinmb** [comment]
I still would like to have a close look at it.

**Comment by steinmb** [comment]
Only re-producible in Firefox so looks like a but in the browser. Here is attempt on a Firefox workaround.  from me.

https://github.com/MachineVisionUiB/machinevision_setup/commit/56b929bd7e3cc7ce0424315c43c9769810320b46
```
 Issue 132 Firefox multi-column workaround

- Refactor code. Remove hardcode field names. This check all node
forms and inject CSS classes on all large form elemnets.
- New class allow us to simplify CSS selectors.
```
