### ISSUE TITLE
Not possible to remove a country from Creative Work

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#133]
If you add two countries to a Creative Work, you can't delete either. Shouldn't there be a way to remove the second country altogether?

<img width="421" alt="Screen Shot 2020-11-30 at 11 33 04" src="https://user-images.githubusercontent.com/44365847/100599065-d7975300-32ff-11eb-9432-01308870411c.png">

**Comment by jilltxt** [comment]
Ah. Actually you can. You just scroll RIGHT up to -None- and poof it's gone. Or did you fix that, @steinmb?

**Comment by steinmb** [comment]
No, that is the default behavior. The UX might be a little confusing this how pulldown form elements often behave.
