### ISSUE TITLE
Hosting system out of disk space

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#135]
I was trying up upload screenshots today, and I was not able to. I tried in different pages and different files, but was not able to. Anybody else experienced this error? It did not happen yesterday though. But there were some weird glitches yesterday, where I was logging a situation or a creative work, and without warning just popped back to the "add content" page. That happenend twice yesterdat, but not so far today.

**Comment by LinnHeidi** [comment]
<img width="865" alt="Screenshot 2021-01-27 at 14 19 51" src="https://user-images.githubusercontent.com/49433622/105997799-4f89bb80-60ac-11eb-8dda-f848742b7156.png">

**Comment by jilltxt** [comment]
I just tried, and get the same error. @steinmb - any ideas?

<img width="712" alt="Screen Shot 2021-01-27 at 14 48 33" src="https://user-images.githubusercontent.com/44365847/106000168-d0e24d80-60ae-11eb-87e1-c03caeeee194.png">

**Comment by steinmb** [comment]
I suspect that the hosting env. did run out of disk space. As simple, and difficult as that perhaps. Let me have a look.

**Comment by LinnHeidi** [comment]
It works now!

**Comment by steinmb** [comment]
As I suspected, we are out of disk space. I have to expand or create a new storage area for the web. application.

```
Filesystem           Size  Used    Avail    Use%   Mounted on
/dev/nvme0n1p1  8.0G  8.0G   43M     100%   /
```

**Comment by LinnHeidi** [comment]
Thank you @steinmb !!

**Comment by steinmb** [comment]
We are not green yet:

Since changing file system is potential risky. Did a extra full sync of db. and files to my local machine. Also created a snapshot of the volume where we store everything on, just if case. I will remove this snapshot when we are done:
  
![Screenshot 2021-01-27 at 16 05 29](https://user-images.githubusercontent.com/683617/106010942-47d11380-60ba-11eb-9b4f-1fc34ccca8b0.png)

The storage area have now been resized, though AWS need to run a optimizer on it before we can use it/full speed:

![Screenshot 2021-01-27 at 16 10 52](https://user-images.githubusercontent.com/683617/106010938-469fe680-60ba-11eb-836a-28b6c6798e60.png)

After this is done will I expand the disk partition where we store our screen shots and videos.

**Comment by steinmb** [comment]
For the record:

After AWS tools are done: `sudo growpart /dev/nvme0n1 1`:

```
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0   8G  0 disk
├─nvme0n1p1   259:1    0   8G  0 part /
└─nvme0n1p128 259:2    0   1M  0 part
```

After change:

```
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  16G  0 disk
├─nvme0n1p1   259:1    0   8G  0 part /
└─nvme0n1p128 259:2    0   1M  0 part
```

And we also need to tune the `volume` with: `sudo xfs_growfs -d /`

```
meta-data=/dev/nvme0n1p1         isize=512    agcount=4, agsize=524159 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1 spinodes=0
data     =                       bsize=4096   blocks=2096635, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal               bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
data blocks changed from 2096635 to 4193787
```

Verify that we got more storage, `df -h`.

```

Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        963M     0  963M   0% /dev
tmpfs           981M     0  981M   0% /dev/shm
tmpfs           981M  388K  981M   1% /run
tmpfs           981M     0  981M   0% /sys/fs/cgroup
/dev/nvme0n1p1   16G  8.0G  8.0G  51% /
tmpfs           197M     0  197M   0% /run/user/1000
```

**Comment by steinmb** [comment]
Reopen. I would like to keep this open for a couple of days and then use it as a reminder to drop the volume snapshot. AWS will bill us pr. snapshot * time.

**Comment by steinmb** [comment]
No side effects detected. Removed volume snapshot backup from Amazon infrastructure.
