### ISSUE TITLE
Data Export Wishlist April 2021

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#137]
This is a list of the data exports we would like prioritised for April 2021. Please add suggestions in the comments.

BIG OVERALL DATA EXPORT
- [x] Probably split the "works" and everything export into Art, Games, Narratives - now it is so big it's impossible to download (or do we need to increase server capacity?)
- [x] Add Country to Work export (this is a new field on Creative Work)

AGENTS AND VERBS - WHO/WHAT IS ACTING; ACTED UPON; HOW IS AGENCY DISTRIBUTED?
We have characters and verbs. Need corresponding exports for entities and technologies. We need to be able to separate these based on whether they are in a game, artwork or narrative (Publication_type is a field on Creative Work), and on which situation they occur in (Title of Situation they are mentioned in).
- [x] Characters and verbs - use existing and add Situation the verb occurs in and Publication_type of the Creative Work the Situation is in. 
- [x] Technologies and verbs + Situation + Publication_type (of Creative Work)
- [x] Entities and their verbs + Situation + Publication_type (of Creative Work)

More distant Wishlist - would be interesting to see if the verbs used are different based on which COUNTRY the work is associated with, what YEAR it was published, and maybe event what TOPICs the work engages with.

**Comment by jilltxt** [comment]
Ragnhild mentioned this in Discord - I think this is covered in the big massive data export of Creative Works - it's just that it's too big and crashes before completing the download. 

- [x] Technologies referenced in digital games (for looking at quantity of tech representation, on work level)
- [ ] Technologies used and referenced in digital games and year (timeline, on work level)

For the overall project, I think it would be cool to have all the work countries of origin and their topics or sentiments in a joint paper.

**Comment by LindaKairus** [comment]
Is it possible to get
Topics (like Hacking) and see what verbs are mostly used (e.g. tricking, hacking, mistaking)
and
Sentiments (like Oppressive) and what verbs are mostly used (e.g. hiding, tricking, etc.)

If it is possible to connect work and situation levels I could imagine some kind of dashboard and then it would be great to be able to filter it out still based on Type (Game, Narrative, Art) and maybe scifi or not.

This would be an amazing tool to look at different aspects of Hacking MV as I been talking about.

**Comment by jilltxt** [comment]
I edited the list at the top of this post based on our [discussion in today's meeting](https://universityofbergen.sharepoint.com/:o:/r/sites/MachineVision/SiteAssets/Machine%20Vision%20Notebook?d=w66381fcb2a954aecb5476dacdae9ef08&csf=1&web=1&e=0dAuZM).

**Comment by steinmb** [comment]
commit MachineVisionUiB/machinevision_config@5a1298e3be1b7c482dfc0de3489eb07bc6a894e2 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Apr 21 12:39:23 2021 +0200

    Crative work can now filter on publication type

    Export from this as it is the "root" node can become
    very large. This allow us to cut down the export size
    and time.


![Screenshot 2021-04-21 at 12 52 44](https://user-images.githubusercontent.com/683617/115542374-83860e80-a2a0-11eb-8ffe-0e2a3b09e18c.png)


* Also upgraded Drupal core and all modules and libraries.
* Had a run in with a 10 months old issue that came back to bite me, again. https://www.drupal.org/project/csv_serialization/issues/3120645#comment-14066348 - Mitigated by us not using that part of the module tough the fix in there could be manually rolled by us until it official fixed if needed. Tested it and it addresses the problem.

**Comment by steinmb** [comment]
@jilltxt when you have the time, please have a look at - https://machine-vision.no/data/agents-and-verbs need your feedback.

A little tricky joining data in those situations and multiple ways of getting to the data. When nesting from work nodes and from the action I bumped into https://www.drupal.org/project/entity_reference_revisions/issues/2799479 -

**Comment by jilltxt** [comment]
This looks great! I can't see issues here? 

The only thing is that it'd be useful to have Technologies on separate lines when there are two techs doing the same thing. Makes the Gephi import easier.

**Comment by steinmb** [comment]
Addressed the technology rows.

commit  MachineVisionUiB/machinevision_config@da501bcfde9984802ab147079a130ea7e272d0a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Apr 29 10:58:51 2021 +0200

    List This technology name and ID on separate rows

    Makes data import into 3-part systems easier.

**Comment by steinmb** [comment]
BTW: Are we done in here?

**Comment by ragsol** [comment]
I looked through the list now and think I see all I need! Will the two exports labeled as "experimental" be available? The actions related to the situations are interesting, and searching actions based on characters would be really helpful!

**Comment by steinmb** [comment]
I suggest we close this and open new issues on a case to case base. Please feel free to disagree with me :)
