### ISSUE TITLE
Classifying/Classified

### ISSUE THREAD

**Issue by LindaKairus** [jilltxt/machinevision#139]
I have checked the rest of the corpus using tech Object recognition, Facial Recognition, AR and Emotion Recognition and these are the works that I have changed. If it is a work authored by you or you are invested in this work please let me know if you don#t agree upon this addition, we can then discuss my arguments that i have left in the notes. 

Change Return (Man tricks service drone) by Linn Heidi
STET (Ursula killed by self-driving car) by Edward
The Last Human (XR_935 is recognising) by Linn Heidi
3% (Emotion Recognition in Interviews) by Sunniva
Jupiter Ascending (Ocular Scan) by Cecilie
Slaughterbots (Mom witnessing murder) by Linn Heidi
Terminator 2 (Terminator scans bikers) by Linn Heidi
My Holo Love (Go Yoo-Jin Protects Holo Glasses) by Linn Heidi
The Social Dilemma (AI manipulates Ben) by Edward
X-Men: Days of Future Past (Sentinels identify mutants) by Ainsley
The Simpsons (Homer scans people) by Linn Heidi
Astral Chain (IRIS tool) by @ragsol 
Iron Man (Combat scene - AR identifies civilians) by @jilltxt 
ANON (Augmented Reality Identifying and Classifying) by Linda but should be checked by @mareinna 
Minority Report (Personalized adds) by Linda but is in Needs discussion
Face Your Feelings (Mimicking emotions) by  @ragsol 

I will add to this list next week if I still find something when I go trough the tech Machine Learning, AI (General purpose), Optical/Ocular Implant. These are the tech the verb is used most often in my artworks corpus and now the additional corpus.

**Comment by jilltxt** [comment]
I'm happy with your changes to Iron Man, Linda. Makes a lot of sense!

**Comment by ragsol** [comment]
I can vouch for 3%, My Holo Love, The Simpsons, The Social Dilemma, Face Your Feelings, and Astral Chain :)
