### ISSUE TITLE
Tag pages should show type of work

### ISSUE THREAD

**Issue by mareinna** [jilltxt/machinevision#14]
When you click on a tag you see all works tagged with the specific tag (see for instance the tag ["Theme:Dystopian"](https://machinevision.elmcip.net/themes/dystopian)). This list currently has columns for titles and authors. These lists should also have a column for "Publication type".

**Comment by jilltxt** [comment]
This would be great, yes.

**Comment by jilltxt** [comment]
This has been fixed.
