### ISSUE TITLE
Navigate by taxonomy terms lists character properties like, gender, race, age. Is this really what we want and why?

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#140]
We are trying to list the character properties in the generic taxonomy term lists. The drawback is, as it is these properties are pr. character even if we do not list the character name here, is that in other taxonomy terms like on Creative work level it do not really work the way we want it to.

## Suggested fix

We try to only expose character related data/colums in the vocabularies used directly by characters. Meaning we try find a way to override this behaviour for only the vocabularies below.

* Age
* Gender
* Race/ethnicity
* Sexuality
* Species 

Example:
* https://machine-vision.no/species/human we list characters title and we should make sure the age, gender and so on is listed.
* https://machine-vision.no/central-topics/ai we list a taxonomy term only used by creative work and we should not expose the character properties.

## original report

>![image](https://user-images.githubusercontent.com/49433732/118974683-657cfe00-b973-11eb-9d48-483f26513311.png)
>All of these are listed as "needs discussion", but they're characters that have no "status", so we can't fix it. It seems as if this goes for several characters in the same list: https://machine-vision.no/record-status/needs-discussion?page=1 Maybe the list started showing characters instead of works and situations?

**Comment by ragsol** [comment]
Update: It's on all the lists? Here's the "AI features in..." list: https://machine-vision.no/technologies/ai-general-purpose-artificial-intelligence
![image](https://user-images.githubusercontent.com/49433732/118975420-49c62780-b974-11eb-8ed4-794a9c28faf3.png)

**Comment by steinmb** [comment]
No bug, but we are trying to list the character properties. Up to now they have just been empty (gender, races etc) the changes introduced the last days make sure we also have data. The drawback as it is these properties are pr. character even if we do not list the character name here.

I agree it looks odd and we could improve what we are trying to expose here. So perhaps the question is, what are we trying to show/epose in this list and why? Kjør debatt:

**Comment by ragsol** [comment]
The problem is that if I want to find my games and click the link on the knowledge base page, I get this: https://machine-vision.no/creative-work-publication-type/game which shows 126 entries, some multiple for the same work, possible due to character entries, but I want that link to show the 75 digital games I have entered. 

@LindaKairus @mareinna @jilltxt have to weigh in here - what do you think?

**Comment by steinmb** [comment]
Yes, and since we also list each game character traits inside pr game in the list, you get more that one row.

**Comment by steinmb** [comment]
I think ideally, if we want to expose these traits it should be aggregated and combined:

```
To the Moon | Creative Work | Human | Female | Black | Adult
To the Moon | Creative Work | Human | Male | White | Adult
To the Moon | Creative Work | Human | Male | White | Elderly
```

To something like:

```
To the Moon | Creative Work | Human | Female, Male | Black, White | Adult, Elderly
```

**Comment by ragsol** [comment]
Based on the conversation today: export character specific traits age, gender, sexuality, species, race/ethnicity only on Character overview lists. In the other lists, try to mimic this or something similar (to only have one entry per work showing in those list)
![image](https://user-images.githubusercontent.com/49433732/119484771-a485c780-bd56-11eb-93b0-be5f9f865fef.png)

**Comment by steinmb** [comment]
@ragsol Tried to add this functionality with these changes and custom code. Take if for a spin. Character related terms should and non character terms should not look the same.

https://github.com/MachineVisionUiB/machinevision_config/commit/d8ad7745ef196cf325fc7cb63df7fe258930246b
https://github.com/MachineVisionUiB/machinevision_setup/commit/0b9684636a8b07e2146f604739a6cd28d3ce7bcd
