### ISSUE TITLE
Find a way to merge duplicated terms

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#142]
In `terms` we have taxonomy terms that is the same, just spelled differently.

## Motivation

Manually changing these are labour intensive and error prone.

## Suggested solution

TBD

**Comment by steinmb** [comment]
@jilltxt - There is https://www.drupal.org/project/term_merge but it is still i a early alpha stage.

I gave the module issue queue a little stir to see if the maintainers respond. I do not have high expectations. The current alpha is a year old.

- https://www.drupal.org/project/term_merge/issues/3203127
- https://www.drupal.org/project/term_merge/issues/3118790
- https://www.drupal.org/project/term_merge/issues/3013117

I think the best solution is rolling our own solution for this.

## Example

```
Node 1 -> Term A
Node 2 -> Term B
Node 3 -> Term C
Node 4 -> Term C, Term B
```

Lets say term C is the one we decide to keep. The end result should be:

```
Node 1 -> Term C
Node 2 -> Term C
Node 3 -> Term C
Node 3 -> Term C
```

**Comment by jilltxt** [comment]
@steinmb I think there is actually a bug in Drupal - or an unfortunate feature. If a free tag is entered twice in one entry, and it's never been entered before, then two SEPARATE taxonomy items are created for the new tag. At least when it's entered in two separate paragraphs in the same entry.

**Comment by jilltxt** [comment]
I think we can close this - we don't need to solve it.
