### ISSUE TITLE
RSS feed and social media links are not using vertical navigation bar

### ISSUE THREAD

**Issue by ghost** [jilltxt/machinevision#147]
Viewing all records based on a taxonomy term, ekample publish state also expose this list as a RSS-feed. Example https://machine-vision.no/record-status/one-person-feels-ok

## Current layout

<img width="565" alt="Screenshot 2021-11-10 at 10 44 24" src="https://user-images.githubusercontent.com/683617/141089613-16c65f28-98a0-4492-9de1-1f1b2d7e9370.png">

## Intended layout

We are extending and overriding Drupal 9.x-experimental core theme, Olivero. The design and style guide places both social media and RSS feed in the left navigation bar. We currently do not place anything there. Here is example from the original design and a [Figma design](https://www.figma.com/file/x5zBLbvoW1jsvyAOt4Gp9I/Olivero-Theme---Public)

<img width="435" alt="Screenshot 2021-11-10 at 10 42 26" src="https://user-images.githubusercontent.com/683617/141090102-fc6440c5-cfb3-45d2-b130-61f7c9c8f5a7.png">

<img width="836" alt="Screenshot 2021-11-10 at 10 42 11" src="https://user-images.githubusercontent.com/683617/141090108-deee3f9b-80d1-43e1-bc1a-e4f9658d1d45.png">

## Suggested fix

* Disable the taxonomy terms view RSS feed.
* No social media links in the left navigation bar.

## Original report
There is a button at the bottom of the page that allows user (**without logging in**) to see and copy the html code, is it on purpose?

![unnamed (1)](https://user-images.githubusercontent.com/91607258/136799594-c94359d9-ac1a-4555-b4f2-a35b3e7f5b67.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/91607258/136799596-2471e047-7ee1-4867-b8bf-c27b51bc3499.jpg)

**Comment by steinmb** [comment]
Not sure  I follow you, where is this button exactly?

**Comment by ragsol** [comment]
I don't understand this case either. What's the issue, @Anya-Schtsch ?

**Comment by steinmb** [comment]
In meeting we have decided to disable the RSS/page-feed. The social network icons is not worth the effort since they are not gong to be around for very long.

**Comment by steinmb** [comment]
Addressed by commit:

MachineVisionUiB/machinevision_config@6d8b80663e495d6ab34c869b33256a693ee46068 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Nov 10 18:20:45 2021 +0100

    Issue 147 Disable tax term RSS feed views page

    We are not going to need this, so disable.
