### ISSUE TITLE
Should user account page be visible to not logged in users?

### ISSUE THREAD

**Issue by ghost** [jilltxt/machinevision#149]
To logged in users we also expose the original author to the article. To the logged in users is it useful because these user profile pages allow us to filter by author.

<img width="594" alt="Screenshot 2021-11-10 at 11 15 54" src="https://user-images.githubusercontent.com/683617/141094999-f3426e1e-4dfe-473c-b808-b2067b37f52c.png">

Not logged in users does not have access to that page:

<img width="630" alt="Screenshot 2021-11-10 at 11 19 22" src="https://user-images.githubusercontent.com/683617/141095570-fbae46b2-ff7e-4614-804b-992f45e74721.png">

so the link does not make much sense to them, how ever we should discuss if access to these pages are something we should open for up for if that would be interesting to a visitor or not.

## Original report
>"Authored by" notion under the articles doesn’t make sense. It is visible to the user without logging in.
>
>Maybe we should make subpages about all contributors with basic information about them? Or just hide the authorship tag?

**Comment by steinmb** [comment]
Care to expand on why it does not make any sense? It would be helpful that you write why something does not make sense or should be there and so on :)

I do not think it is useful that the author is linked to when the user viewing the article does not have permission to view the author profile.

**Comment by ragsol** [comment]
I think the author and author profile should be hidden. It's not a valid way of sorting because a lot of entries were made by one person but filled in by others.

**Comment by steinmb** [comment]
We have decided in meeting to hide this field to users not logged in. Going to be addressed in issue #148
