### ISSUE TITLE
Change machine P.O.V. on/off label?

### ISSUE THREAD

**Issue by ghost** [jilltxt/machinevision#150]
The way it is wtitten now is a bit confusing.  Maybe change to “Yes/No”?
![unnamed (4)](https://user-images.githubusercontent.com/91607258/136801231-3605ee5f-d924-4dc8-af1e-a58cdc745b6b.jpg)

## Example situation

* https://machine-vision.no/machine-vision-situation/clandestine-hacker-pov

**Comment by steinmb** [comment]
I have personally no opinion for or against altering the labels. I will leave that up to you to decide.

Technical stuff: The field `node__field_machine_p_o_v` is a simple boolean field and changing the labels is does not alter the values stored and exported from the database. It is still only `1` or `0`.

![Screenshot 2021-10-18 at 09 43 19](https://user-images.githubusercontent.com/683617/137688955-91dfbd88-ae1e-4a45-b109-6d6a93d1da07.png)

**Comment by ragsol** [comment]
I agree that yes/no might be clearer. @jilltxt @mareinna @LindaKairus ?

**Comment by steinmb** [comment]
Closing as "will not fix"
