### ISSUE TITLE
Things to remember to include/exclude from final datasets

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#151]
See the [Data in Brief paper draft](https://universityofbergen.sharepoint.com/:w:/s/MachineVision/EW7WcKCKbn9ArfnMUGFCmPABes6W9Vyf6KUPJt0K4EXVtA?e=rgtjZ2) for details. 

- [x] Include age, gender, species, race in situations.
- [x] Check whether there are creative works where scifi tag is neither on nor off - go through and fix.
- [ ] Do no include characters that have no actions in final dataset (simplest fix: just delete from export after export is done) (see #112 )
- [ ]

**Comment by steinmb** [comment]
I'll check char. export then

**Comment by jilltxt** [comment]
No longer needed.
