### ISSUE TITLE
UiB English project page link to machine-vision.no should perhaps point to the site front page?

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#152]
When you go to https://www.uib.no/en/machinevision there is a article about the db. But that section of text links to the knowledgebase landing page, not the site front page. Perhaps we should change that? 

<img width="665" alt="141081979-6fb18cb6-9dc3-404a-83e7-f40656324138" src="https://user-images.githubusercontent.com/683617/141083432-2a321c07-b73e-4307-8488-c2cc26a7a530.png">

@Anya-Schtsch found that confusing trying to find out about the project the first time. First going to the UiB page, following the link to the mv-site.

**Comment by steinmb** [comment]
The Norwegian does not have a article/section linking to the mv-site like this at all from what I can se...

**Comment by ragsol** [comment]
Agreed! This is super important!

**Comment by jilltxt** [comment]
Added this.
