### ISSUE TITLE
Fix these situations and characters

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#154]
Incomplete situations: 

- [x] https://machine-vision.no/machine-vision-situation/ancillary-justice-ai
- [x] https://machine-vision.no/machine-vision-situation/has-anyone-else-used-expressioncaptioner-emotion-recognition
- [x] https://machine-vision.no/machine-vision-situation/ai-aint-i-woman-facial-recognition
- [x] https://machine-vision.no/machine-vision-situation/facial-features-not-recognized-facial-recognition (missing an agent)
- [x] https://machine-vision.no/machine-vision-situation/hunger-games-holo (missing an agent)

Incomplete characters: 

- [x] https://machine-vision.no/character/one-esk-nineteen
- [x] https://machine-vision.no/character/john-anderton
- [x] https://machine-vision.no/character/veronique-ducharme
- [x] https://machine-vision.no/character/hayley
- [x] https://machine-vision.no/character/ellie
- [x] https://machine-vision.no/character/heartless-self-professed-troll 
- [x] https://machine-vision.no/character/girl-im-going-die-and-probably-soon
- [x] https://machine-vision.no/character/narrator-im-going-die-and-probably-soon
- [x] https://machine-vision.no/character/narrator-my-camera-knows-somethign
- [x] https://machine-vision.no/character/narrator-i-created-ai
- [x] https://machine-vision.no/character/monster-im-going-die-and-probably-soon
- [x] https://machine-vision.no/character/narrator-satellite-images
- [x] https://machine-vision.no/character/google-maps-girl-satellite-images
- [x] https://machine-vision.no/character/professors-son-drones-dont-kill-people
- [x] https://machine-vision.no/character/professors-daughter-drones-dont-kill-people

**Comment by jilltxt** [comment]
@mareinna, [Hayley's](https://machine-vision.no/character/hayley) only verb is "dead" so I think we should delete the character. Unless there is actually something else Hayley is doing or having done to her. Possible verbs: altered, sexualised?
But really it's the image not the person who is altered - although it's not insignificant that its a young woman. 
https://machine-vision.no/machine-vision-situation/thoughts-and-prayers-deepfake

**Comment by ragsol** [comment]
... and these! https://github.com/MachineVisionUiB/machinevision/issues/128
