### ISSUE TITLE
Two Entities or Characters in the same cell

### ISSUE THREAD

**Issue by LindaKairus** [jilltxt/machinevision#157]
When I import the situations CSV (export from website) into excel in some few cases there is still two entities or characters in the same cell, like wise the Id numbers are there. They are separated by a comma, but of some reason the excel does not read it. Is there something we can do to it in the export? or should it be cleaned afterwards?

<img width="299" alt="Screenshot 2021-12-02 at 10 20 36" src="https://user-images.githubusercontent.com/16516978/144566324-02c66943-c386-4b19-b8e7-e597c8d5f19a.png">

<img width="481" alt="Screenshot 2021-12-02 at 10 21 11" src="https://user-images.githubusercontent.com/16516978/144566341-0a6675ad-f504-41ec-80ea-c0ba1f93898b.png">

**Comment by steinmb** [comment]
Hei Linda
Where did you find this file?

**Comment by LindaKairus** [comment]
The sitiuations_long_v2 (1) did not have this issue anymore, so I close it.
