### ISSUE TITLE
Delet: Jiminy (Man Zooms in on Cricket)

### ISSUE THREAD

**Issue by LindaKairus** [jilltxt/machinevision#158]
The situation Jiminy (Man Zooms in on Cricket) by Linn Heidi is not connected to any work. Perhaps the work was deleted, but not the situation. Jill can you with admin rights still make the situation a draft, then it should not export it or delete it.

https://machine-vision.no/machine-vision-situation/jiminy-man-zooms-cricket

**Comment by jilltxt** [comment]
I deleted this and saved a web archive of the page to Database/Deleted from database.
