### ISSUE TITLE
Plan the Solstrand workshop, June 6-7

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#16]
- [x] make a schedule
- [x] discuss the big picture - are we missing something to answer the research questions?
- [x] discuss definitions
- [x] Book location
- [x] Book breakfast, lunch, dinner etc.

**Comment by jilltxt** [comment]
Probably talk with Annette beforehand too - plan to do some of her more speculative methodologies to think through our methodologies and the coding scheme?
