### ISSUE TITLE
Missing verbs

### ISSUE THREAD

**Issue by LindaKairus** [jilltxt/machinevision#164]
In Superintelligence (AI observes Carol)
https://machine-vision.no/machine-vision-situation/superintelligence-ai-observes-carol
This technology AI (General Purpose Artificial Intelligence) is blank
(a Narrative added by Linn Heidi) 

The others on my list were already changed.

**Comment by jilltxt** [comment]
I added the same verbs to the technology AI as the character Superintelligence has, since the character *is* the AI. There are a LOT of verbs - my impulse is to remove some but I haven't seen the work so maybe just leave it? Does this seem OK to you, @LindaKairus

**Comment by LindaKairus** [comment]
Yes, I think it is best to keep the same verbs. So if you added the same verbs to the technology AI as the character we can close this issue.
