### ISSUE TITLE
Improve Machine vision site/main front page

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#18]
What content should live on the front page https://machine-vision.no/, and how should look like?
Issue #3 is now done and we are free to customize our theme.

## Current site front page

![Screenshot_2019-06-19 Machine Vision Database Machine Vision](https://user-images.githubusercontent.com/683617/59754884-49541c00-9287-11e9-992a-78a07ed41b83.png)

## Updated front page

![Screenshot_2019-08-17 front page Machine Vision](https://user-images.githubusercontent.com/683617/63215077-596e6780-c121-11e9-92ca-b1a6b9fbbcbb.png)

## Suggested wire frame
![IMG_6637](https://user-images.githubusercontent.com/44365847/59914533-e0051200-941a-11e9-8ef8-2a2b97a6bb9d.jpg)

## How to test

Verify that page render correctly on mobile devices, tablet and all major desktop browsers.

**Comment by LinnHeidi** [comment]
I think we should get a color combination that complements the trademark.
- Also I think the layout in every entry looks a bit messy, so maybe we can discuss how we can make it more streamlined in the look.

**Comment by jilltxt** [comment]
Also see https://github.com/jilltxt/machinevision/issues/33 - which is about the "Knowledge Base" page, not the front page. This should be fixed or at least improved before NORDMEDIA, ideally.

**Comment by steinmb** [comment]
Updated the issue summary to make sure we understand what we are trying to improve. This issue only try to address the site front page https://machinevision.elmcip.net/

**Comment by LinnHeidi** [comment]
![MV_gif](https://user-images.githubusercontent.com/49433622/59908717-564f4780-940e-11e9-9ef1-af0f0f11289a.gif)

**Comment by steinmb** [comment]
New front page and header. Still lacking the UiB logo though.

## Updates to site theme

commit 4fcaff8d9b32b3c24b74272ab75fc079a807cba8 (HEAD -> master, origin/master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 18:55:21 2019 +0200

    Issue 18 Reduce front page intro text size on smaller screens

commit 6e3294dbd056ce338121344b19e23610e6c3ecea
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 18:31:36 2019 +0200

    Compiled CSS

commit 0d2c47722e8f9dd3d1bd302516b108f130d9f86f
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 18:30:44 2019 +0200

    Issue 18 Alter navigation menu default hover and active states

    The hover and active states does no look OK with a larger and expanded
    navigation menu. Active state is also a little hard to see. This add
    a solid bottom border to the active element.

commit e7b31d0c13de37df49dbb704a1ccc4088a6a14c4
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 18:00:34 2019 +0200

    Issue 18 Landing page full width mixin and font settings

    - SASS mixin that allow us to stretch elements outside the container
    element.
    - Introduce a header wrapper that allow the header to grow outside
    page wrapper.

commit 941eca03c4c91437155b34baff0beb1c5bfc0961
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 15:29:46 2019 +0200

    Issue 18 Remove page title from landing pages

    Not needed on these pages

commit 23618b82ebdb6b112fbbd99b479c413053735fc1
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 14:28:43 2019 +0200

    Issue 18 Create content type page template suggestions

commit 85024d83a1d4f70fa90df157ddba7954becea5a9
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Sat Aug 17 14:28:02 2019 +0200

    Issue 18 Landing page template init


![Screenshot_2019-08-17 front page Machine Vision](https://user-images.githubusercontent.com/683617/63215077-596e6780-c121-11e9-92ca-b1a6b9fbbcbb.png)

**Comment by jilltxt** [comment]
This is fine for Nordmedia but I think we'll need to discuss more what should be here. Actually, I'm thinking maybe we should remove this page altogether and make the landing page the first page people see, but let's discuss after Nordmedia?
