### ISSUE TITLE
Improve reccords layout and style

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#19]
Issue #3 is now done, unblocking custom styles for our records. 

Related issue is #18 addressing the site front page.

### Desktop view

![Screen Shot 2019-05-27 at 15 14 21](https://user-images.githubusercontent.com/683617/58422366-aa2a7300-8092-11e9-858c-a5822f032d9b.png)

### Iphone 6,7,8,10 and 10S vertical mode

![Screen Shot 2019-05-27 at 15 15 56](https://user-images.githubusercontent.com/683617/58422381-b4e50800-8092-11e9-89b1-ea1af5bad3f6.png)

**Comment by LinnHeidi** [comment]
We need to figure out how these pages should look, now that we also include character and situation (MESSY!)

**Comment by jilltxt** [comment]
Closing this - we'll need to fix display more of course but not right now.
