### ISSUE TITLE
I messed up - now Creative Works don't display Situations

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#25]
I'm not sure what I did, maybe because I added a layout to Situations, since they got so complex? But whatever happened, you can still ADD situations to Creative Works, but when you view a Creative Work it doesn't show information about or a link to the Situations it is linked to. Sorry...

**Comment by ragsol** [comment]
Situation appears on "AI, Ai'nt I a Woman", but not on "Her"... What the fudge? (Stokkedal, 2019)

**Comment by jilltxt** [comment]
Maybe situation appears on older entries but not new ones? @steinmb, I'm hoping you can help fix this...

**Comment by jilltxt** [comment]
Fixed.
