### ISSUE TITLE
Character issues

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#27]
- [x] How do we tag for people of Asian descent?

- [ ] Is agency increased, same, or decreased when you get more visual information but cannot necessarily act upon it?

- [ ] How do we define the operator e.g. in the film "Her", where there is an AI operating system and a "user"?

- [x] Remove "Cyborg" from "Race"

- [x] Consider adding a "Gender not emphasized"?

_Removed and made a new separate issue: Character list and situations list don't match - probably need to be the same to avoid confusion in the exports._

**Comment by jilltxt** [comment]
I will ask Radhika Gajjala about a good way of classifying the representation of race. Should we include e.g. Asian, Arabic, Indian, Latin American?

Gender/Race: Add not applicable (use if race/gender is not applicable, for istance for R2D2 race and value don't apply. Remove not emphasized, leave blank if race/gender aren't represented or mentioned in the work.

**Comment by jilltxt** [comment]
Closed: these problems are either solved or no longer relevant :)
