### ISSUE TITLE
Replace episodes with situations?

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#32]
Because of the new coding system, there might not be need to register all episodes or game editions in a franchise. Instead, we can register the overall work's title as a work, and list the different machine vision situations as "Situations". This way, we'll keep the database entries "level" and still have all the information we need. It will also simplify (A LOT) for games :)

**Comment by jilltxt** [comment]
Ooh, that's an excellent idea. +1, and let's make a decision on this on Thursday.

**Comment by jilltxt** [comment]
Make one entry for each season or group of episodes - e.g. Black Mirror (season 1). Episodic games can be grouped similarly. To preserve information about the year of publication, don't group episodes that are more than two years apart. Use the publication year of the first work.
A situation can in some cases be connected to more than one work. For instance, if the Tardis was a machine vision technology, we could have one situation for the Tardis that was connected to multiple seasons of Doctor Who.

**Comment by jilltxt** [comment]
Reopening - Ragnhild, can you please add this to the Wiki?
