### ISSUE TITLE
Database landing page: what links should be included (NOT front page of whole site)

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#33]
## Customise KB landing page
- https://machine-vision.no/knowledgebase)
- Creative works (title, year, type (i.e. game, movie, etc)
- Situtations (tittel)
- List of (linked) tags from these vocabularies: Themes, Technology Used/Technology Referenced (merged if possible), Sentiments. Ideally, these vocabularies will be displayed as clickable wordclouds, sized for frequency of use.

## Wireframe from meeting 12.06.2019

![IMG_6638](https://user-images.githubusercontent.com/44365847/59914740-4853f380-941b-11e9-8c5e-1ec878ad6ecb.jpg)

**Comment by jilltxt** [comment]
We need help from @steinmb for this. We should decide exactly what we DO want on the front page - do we need platform? What order should things be in? Should we include some of the tags?

**Comment by LinnHeidi** [comment]
I like the idea of having tags on the front page!

My preferred order would be:
Creative works
Situations
Characters
Persons
Tags (either the the most used, or last used?)

**Comment by steinmb** [comment]
Removed as much clutter as I could. Small changes to code but mostly to site config.

commit 8646d0ab45e25adeb1c6baf369cb1b07a8f3bf1d (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Aug 16 18:49:35 2019 +0200

    Issue 39 Alter Views read more markup to use Bootstrap anchor elements

    In KB list of data do these read more links lack visual weight making
    end users overlook them.


## Desktop large screen

![Screenshot_2019-08-16 Machine Vision Knowledge Base Machine Vision(1)](https://user-images.githubusercontent.com/683617/63184203-1ba50c80-c057-11e9-87ea-9b5bc0fb99e1.png)

## Desktop small screen / Tablet

![Screenshot_2019-08-16 Machine Vision Knowledge Base Machine Vision(2)](https://user-images.githubusercontent.com/683617/63184301-5444e600-c057-11e9-93d5-84050486c217.png)

## Small screen aka phones

![Screenshot_2019-08-16 Machine Vision Knowledge Base Machine Vision(3)](https://user-images.githubusercontent.com/683617/63184358-72aae180-c057-11e9-98a0-459d8de8c419.png)

**Comment by steinmb** [comment]
As a starting point for further discussion here. What about `Characters and Persons`. They are not present in the photo but @LinnHeidi mention them.

**Comment by jilltxt** [comment]
This looks fantastic, thank you!! So much cleaner!!! I’m sure we’ll want to tweak a few things but this is great for the workshop :)

**Comment by LinnHeidi** [comment]
This looks so good! I am a fan!

________________________________

**Comment by jilltxt** [comment]
I think this is great for now. I think we'll want to move things around a bit later but it's absolutely fine for Nordmedia, so I'll close the issue :) 

I showed the database to Mathias Klang (our new Fulbright Nora's husband, who is also a media scholar) and he liked it a lot, but would have liked a clearer explanation of what it was in the top text - I can edit that before the workshop.
