### ISSUE TITLE
Fix "Create Person" page

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#38]
Something has happened to this page!

**Comment by jilltxt** [comment]
Not sure what happened here. I removed the stray fields that were at the top, that we don't use. I can't remember how we had set this page up - does it look right now? We can alter things.

**Comment by LinnHeidi** [comment]
It looks great now, but should we keep or remove the "Biography?" We have to make a decision, because if we are going to use it, we need to include it in the WIKI.

**Comment by jilltxt** [comment]
I will 
remove biography and then close this issue.
remove residency
make nationality into "country"
make multiple choices possible for country
remove gender
remove email
Then close this issue.

**Comment by jilltxt** [comment]
Done.
