### ISSUE TITLE
Video media elments overflow its container and breake layout

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#39]
![Untitled](https://user-images.githubusercontent.com/49433732/59659203-feaea300-91a5-11e9-8590-5e463a9150b4.jpg)

From [https://machinevision.elmcip.net/content/pok%C3%A9mon-go-augmented-reality](https://machinevision.elmcip.net/content/pok%C3%A9mon-go-augmented-reality)

**Comment by steinmb** [comment]
Thank you. Could you also update the report to include the url to the record pretty please, with sugar on top?

**Comment by jilltxt** [comment]
See also issue #41, which I closed since it is about the same issue.

**Comment by steinmb** [comment]
This should take care of this

commit 8e4cd31fe70e597ffab1e9c82b2bad839266a810
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Aug 16 17:36:16 2019 +0200

    Issue 39 Make sure video iframe do not overflow container

    Vimeo, Youtube and so on inserts iframes that we need to control. This
    also make sure file elements like video, image and so on is separated
    with withe space since they are multi value fields.

**Comment by jilltxt** [comment]
The video embeds now look great, but still images look a bit dodgy on my Mac. 

VIDEO example
<img width="1083" alt="Skjermbilde 2019-08-19 kl  11 34 33" src="https://user-images.githubusercontent.com/44365847/63255274-ac593380-c275-11e9-96f3-046ec16ad866.png">

STILL IMAGE example
<img width="1034" alt="Skjermbilde 2019-08-19 kl  11 36 35" src="https://user-images.githubusercontent.com/44365847/63255286-b2e7ab00-c275-11e9-82a0-d4473ba6f21b.png">

**Comment by steinmb** [comment]
Good catch. Fixed in 

commit e4375b4a150f3530fa1a6cce5df5b841dd618212 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Aug 22 08:20:07 2019 +0200

    Issue 18 Fix - Make sure full width front page image do not affect other images

    - Addresses side affect on creative work screen shots.
