### ISSUE TITLE
Formatting of "Multimedia" does not fit the "Situations" boxes

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#41]
Looks messy when you enter "Situation", the videos (not the screenshots I think) are overcrossing the frames of the boxes.

**Comment by jilltxt** [comment]
I set the layout to two-column and then couldn't figure out how to set it back again when I realized the videos are too wide for that layout. I'm quite happy for a different layout to be implemented!! Would be great to have something that looks OK by NORDMEDIA (20 Aug).

**Comment by steinmb** [comment]
That is in the works. I'll handle the layout thingies. The 50/50 split is prob. not what we want anyway. The page width is flexible so...

**Comment by LinnHeidi** [comment]
This issue overlaps with issue #39 Sorry for not noticing!

**Comment by jilltxt** [comment]
I'll close this issue since there is an overlap, and I'll add a reference from issue #39.
