### ISSUE TITLE
Find the line about funding that needs to be put at end of all publications

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#42]

**Comment by jilltxt** [comment]
All publications and dissemination of results from the project needs to have the following text at the bottom. The ERC logo should also be displayed if possible. This includes book chapters, journal articles, books, etc. 

This project has received funding from the European Research Council (ERC) under the European Union’s Horizon 2020 research and innovation programme (grant agreement No 771800).

<img width="625" alt="Skjermbilde 2019-06-18 kl  11 46 15" src="https://user-images.githubusercontent.com/44365847/59671881-c1a2da80-91be-11e9-8394-ae7c22809a49.png">
![Tell](https://user-images.githubusercontent.com/44365847/59671886-c36c9e00-91be-11e9-8781-a530aa9a3268.png)

See https://erc.europa.eu/managing-your-project/communicating-your-research

**Comment by steinmb** [comment]
The site currently have the following text on the page bottom of every page, ref #https://github.com/jilltxt/machinevision/issues/3#issuecomment-481152498
 
`This project has received funding from the European Research Council (ERC) under the European Union’s Horizon 2020 research and innovation programme (grant agreement No 771800).` 

but if I understand you righ. We also need something mention above also inside every record?

**Comment by jilltxt** [comment]
No, I think the text at the bottom of the page is good enough, though we should probably add a logo. We need to put this on EVERYTHING though, like presentations and publications and even on a sticker underneath the Playstation in the office.

**Comment by steinmb** [comment]
Ooops. did not intend to hijack the issue.

commit 286dc5a35eff9dc506adcc3b047bc356cb12deaa (HEAD -> master, origin/master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Jun 18 12:27:36 2019 +0200

    Added ERC logo to machinvision theme

**Comment by LinnHeidi** [comment]
Books too then?

**Comment by steinmb** [comment]
This use ERC logo prev. added to the theme and correctly position it with the generic text

commit d0e800a52eecc8c6bb51e97c3cc0f0cd0ffb562d (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Jun 18 16:33:44 2019 +0200

    Generic way of controlling sponsors layout

    media and bottom aligned text.

**Comment by jilltxt** [comment]
This looks great now, thanks!
