### ISSUE TITLE
Print stickers for equipment acknowledging ERC funding

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#43]
@LinnHeidi, could you please figure out how to print a few (10-15) stickers we can put on equipment bought with the project funding? Our laptops are NOT bought with project money (but by the department) but the Playstation was bought with project money, and other stuff may be. We are supposed to put stickers with a specific text on to the equipment. The stickers can be generated here. The grant number  is 771800. http://ec.europa.eu/research/participants/data/ref/h2020/other/gm/stickers/h2020-stickers-equip.html
You may want to ask Allkopi or whoever prints stuff for UiB if they can print them? Or perhaps it's easy enough to ask Steinar for sticker printing paper and print?
This needs to be done, but isn't urgent - by the end of the summer would be good though.

**Comment by LinnHeidi** [comment]
I am on it!

**Comment by jilltxt** [comment]
Not books, just equipment like the PlayStation and perhaps also the VR headset. And ha, if it’s really, really big equipment it says we can get a plaque instead of a sticker but I doubt we’ll need that....
