### ISSUE TITLE
Add scanning? "What is the machine vision doing in this specific situation?"

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#44]
in the Situation: "What is the machine vision doing in this specific situation?"

Example: in Ocean`s 8, they are using machine vision only to scan a necklace, in order to make a copy of it.

**Comment by jilltxt** [comment]
I think that’s “recording”, isn’t it?

**Comment by LinnHeidi** [comment]
And what about Playing?

And I don`t agree on that "recording" and "scanning" is the same.

**Comment by jilltxt** [comment]
This is now being discussed in thread #45, so I'm closing this issue.
