### ISSUE TITLE
Move Machine vision to machine-vision.no

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#47]
We currently use a ELMCIP subtheme. Perhaps we should have our own. It is a matter of finding on, buy it, own it and apply it to the DNS and servers.

**Comment by jilltxt** [comment]
Yes, this is definitely a good idea. These domains are available:
http://machinevision.nu
http://machvision.net
http://machinevisionineverydaylife.no, .com, .net, .org etc

But if the main thing we'll store on this domain is the database, perhaps we should think of a domain name that is more specific to the database?

**Comment by jilltxt** [comment]
Http://machine-vision.eu is available - Jill will buy.

**Comment by ragsol** [comment]
Det ser ikke ledig ut nå... kom inn på noe sketchy greier her, i alle fall O.o

**Comment by jilltxt** [comment]
I bought http://machine-vision.no today. We can set up in August.

**Comment by steinmb** [comment]
Still waiting for DNS to fully update changes though I have generated cert.  for the site and updated all server config.

```
Congratulations! You have successfully enabled https://machine-vision.no

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=machine-vision.no
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/machine-vision.no/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/machine-vision.no/privkey.pem
   Your cert will expire on 2019-11-10. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - Some rewrite rules copied from /etc/httpd/conf.d/machinevision.conf
   were disabled in the vhost for your HTTPS site located at
   /etc/httpd/conf.d/machinevision-le-ssl.conf because they have the
   potential to create redirection loops.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

```

**Comment by steinmb** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=machine-vision.no

**Comment by steinmb** [comment]
@ragsol @jilltxt @LindaKairus @mareinna  just got it verified and we should start using it.
