### ISSUE TITLE
Change title of database to "Machine Vision Database"

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#49]
Suggestions?

**Comment by ragsol** [comment]
I suggest "Machine Vision Database" in the link header (the static) and the gif says "Machine Vision in Everyday Life". I don't think we need an extra title, because we can put the "cultural representations ..." in the text below the gif. Imo :)

**Comment by steinmb** [comment]
@ragsol wrote:
> I suggest "Machine Vision Database" 

+1 to that

**Comment by jilltxt** [comment]
Yes, this sounds good to me too.
