### ISSUE TITLE
Matching the tags for characters and groups/situation operators and viewed

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#53]
I did a thing. I've gone through the lists and tried to find places where they don't match. Here's a suggestion on how to make the two lists (one created in the old system and one in the Solstrand system) more compatible, so as to make both tagging and exports easier :)
- Green is create
- Yellow is change/move
- Red is delete (or suggestion to delete)

If there's no color, there's no need to fix it! Obviously, the Group List will be a little bit different, but I think there's value in getting them as similar as possible.

![Characters and group characters](https://user-images.githubusercontent.com/49433732/59919612-33319180-9428-11e9-9130-8d1bbd8e52db.png)

**Comment by jilltxt** [comment]
I love how organized you are, Ragnhild! Thank you!

**Comment by jilltxt** [comment]
Ragnhild and I added to terms to Race/ethnicity: Asian and Multiple/Complex.

**Comment by jilltxt** [comment]
We should discuss this and decide whether to implement in db as is, or with changes.

**Comment by ragsol** [comment]
This is not updated with Asian

**Comment by jilltxt** [comment]
Fixed with new system.
