### ISSUE TITLE
Remove map link from Person (author/artist/creator) display

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#54]
Update: Probably the map link will disappear with Drupal upgrade. Check and see. 

![person](https://user-images.githubusercontent.com/49433622/60657132-0bdbbb00-9e51-11e9-8a54-0ebe22931f7d.png)

"Country" on the "Person" page appears differently when you are making a new entry and when you edit a page. I think we want the version on the "Edited page"? Have a look!

**Comment by jilltxt** [comment]
Hm, I think this is just a quirk of the software, I can't see any way to change it and it doesn't really affect the output, so maybe just leave it this way?

**Comment by LinnHeidi** [comment]
Also when you go into a "person" it will look like this.
![person](https://user-images.githubusercontent.com/49433622/65411253-af9f8c00-ddec-11e9-967b-fd59b308b800.png)

I don`t think we need the map link there.

**Comment by jilltxt** [comment]
I agree - but I can't see how to turn off the Google maps link. We will ask Stein Magne - but it might just be built into the system.

**Comment by jilltxt** [comment]
We will see how this looks after the upgrade.

**Comment by steinmb** [comment]
Re-visited this. Out of the box is this how country information is displayed for persons.

##  Person

![Screenshot 2020-08-04 at 08 52 36](https://user-images.githubusercontent.com/683617/89262482-f591c700-d62f-11ea-8d8f-1eb5f9ceaab8.png)


Adding/changing country information, aka the forms, look like this:

## Edit node

![Screenshot 2020-08-04 at 08 54 44](https://user-images.githubusercontent.com/683617/89262680-37bb0880-d630-11ea-898a-824f4e33344f.png)

**Comment by steinmb** [comment]
No feedback, consider this fixed. Closing.
