### ISSUE TITLE
Implement and test new situations setup

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#63]
Stein Magne and I have added the "what is who doing" section to the test database ([http://test.machine-vision.no/knowledgebase](http://test.machine-vision.no/knowledgebase)). Please help us by [entering a few situations](https://test.machine-vision.no/node/add/machine-vision-situation) so we can see if it works the way we want it to. 

- [x] Enter a few of the Solstrand examples to see if it works (don't get detailed with the descriptions, screenshots etc since this is just the test database - just focus on the Actions and the Visuals).
- [x] Comment here about problems or if it works
- [x] Think about what to call the different items ("Actions"? "Things"? "Other"? Need better terms.)
- [x] Friday morning: Jill implements new situations in main database, we test a bit there.
- [x] On Monday we discuss with Stein Magne, make any last changes and hope it's good to go

Jill's stuff on Monday:

- [x] Fix situations 
- [x] Add sentiments to Creative Works and hide from Situations
- [x] Change order of Gender and Race in Characters
- [x] Characters before Situations in Creative Works

I've moved all the stuff we DON'T need anymore in situations down, please ignore everything on the edit page after "Research Notes".

To test:  Below the overall description and screenshots you'll find this:

<img width="614" alt="Skjermbilde 2019-10-23 kl  12 02 59" src="https://user-images.githubusercontent.com/44365847/67382978-ad1c8780-f58e-11e9-8bda-06d0f777d8f8.png">

Select the _type_ of paragraph (are you entering information about technology, a character, or about _things_ (need a better name for that). Then click Add Paragraph.

<img width="507" alt="Skjermbilde 2019-10-23 kl  12 08 01" src="https://user-images.githubusercontent.com/44365847/67382550-f1f3ee80-f58d-11e9-83a0-0304935f04e1.png">

You can select the type of technology, or type in the Character name (which must already have been entered as a separate node in the database), or type in any word for a "thing", for instance the Creator (person who made the work - artist, author etc), Image (in the case of deepfakes), maybe even bacon, I'm not sure whether we should try to limit the number of different things here. Groups or corporations might go in the Things list - we need to discuss when to put stuff as "Things" and when to create a character.

Type each -ing verb in a comma-separated list. The UI isn't very good so it looks as though they're not being entered. When you save the whole situation it will be saved, though. For "passive" actors/agents/things, type "passive" but also consider using passive verbs ending in -ed (altered, killed). We can sort this later. 

My hope is that by NOT defining entities as "actors" or "objects" or "subjects" or "operators" or "tools" but using verbs we can avoid the subject/object binary while still allowing for useful analysis afterwards. It also simplifies data entry a lot. 

There's also spaces for Visual info to try out. 

<img width="394" alt="Skjermbilde 2019-10-23 kl  18 11 12" src="https://user-images.githubusercontent.com/44365847/67412955-8f681600-f5c0-11e9-80a1-ae71dcfa6fc3.png">

Same as above, comma separated list for tags, and remember to save the form.

**Comment by jilltxt** [comment]
Stein Magne and I have added the "what is who doing" section to the test database. Please help us by entering a few situations so we can see if it works the way we want it to. Tomorrow afternoon, if it works out, I'll move this to the real database, and we can test some more. On Monday we'll discuss whether more changes are needed. We need to think about what elements are called, the titles are a bit odd right now. Also, I've moved all the stuff we DON'T need anymore in situations down, please ignore everything on the edit page after "Research Notes".

To test:  Below the overall description and screenshots you'll find this:

![Uploading Skjermbilde 2019-10-23 kl. 12.02.59.png…]()

Select the _type_ of paragraph (are you entering information about technology, a character, or about _things_ (need a better name for that). Then click Add Paragraph.

<img width="507" alt="Skjermbilde 2019-10-23 kl  12 08 01" src="https://user-images.githubusercontent.com/44365847/67382550-f1f3ee80-f58d-11e9-83a0-0304935f04e1.png">

You can select the type of technology, or type in the Character name (which must already have been entered as a separate node in the database), or type in any word for a "thing", for instance the Creator (person who made the work - artist, author etc), Image (in the case of deepfakes), maybe even bacon, I'm not sure whether we should try to limit the number of different things here. Groups or corporations might go in the Things list - we need to discuss when to put stuff as "Things" and when to create a character.

Type each -ing verb in a comma-separated list. The UI isn't very good so it looks as though they're not being entered. When you save the whole situation it will be saved, though. For "passive" actors/agents/things, type "passive" but also consider using passive verbs ending in -ed (altered, killed). We can sort this later. 

My hope is that by NOT defining entities as "actors" or "objects" or "subjects" or "operators" or "tools" but using verbs we can avoid the subject/object binary while still allowing for useful analysis afterwards. It also simplifies data entry a lot.

**Comment by mareinna** [comment]
Hi, I tried to do a short test by entering Sight from the spreadsheet. I think it looks grat, albeit still ab bit chaotic because the old system is still there as well. My only comments are minor:

Workflow: I think it would make sense to put characters before situations, just because we have to refer to the characters when we fill in the situations, which means scrolling down to make the characters and then back up again.

Characters/workflow: If it's not a big task, can we reorder the attributes so it's gender, then race int he character nodes? I keep trying to write gender in the race box because that's how it's usually ordered in other forms.

Technologies: I am wondering what we do when there are a series of technologies (in the case of Sight: AR, occular implant, emotion recognition) working as an assemblage to perform the same action? It doesn't seem to make sense to enter them all in as different technologies with the same verbs, but giving the all different verbs, albeit possible, seems to obscure more than it reveals. Is it possible to highligt more than one tech from the list and assign them all the same verb box? Or would that introduce more problems?

**Comment by ragsol** [comment]
- Where is sentiment now? Hidden on both layers
- Is a corporation a "Thing" or a "Character"?

**Comment by jilltxt** [comment]
Marianne: 
> Workflow: I think it would make sense to put characters before situations, just because we have to refer to the characters when we fill in the situations, which means scrolling down to make the characters and then back up again.

Done (in the main database)

> Characters/workflow: If it's not a big task, can we reorder the attributes so it's gender, then race int he character nodes? I keep trying to write gender in the race box because that's how it's usually ordered in other forms.

No problem, done. 

> Technologies: I am wondering what we do when there are a series of technologies (in the case of Sight: AR, occular implant, emotion recognition) working as an assemblage to perform the same action? It doesn't seem to make sense to enter them all in as different technologies with the same verbs, but giving the all different verbs, albeit possible, seems to obscure more than it reveals. Is it possible to highligt more than one tech from the list and assign them all the same verb box? Or would that introduce more problems?

Yes, we can select multiple technologies (or multiple characters) and give them the same verb. If a tech and a character are working as an assemblage, give them the same verb. I think that works well in the export too. 

E.g. facial recognition, ocular implant --> identifying, analyzing
Anna (a character) --> identifying, analyzing

If Anna or the ocular implant are also doing things that aren't working together as an assemblage, I don't think it matters much how you enter it (Anna --> identifying, analyzing, killing vs Anna --> identifying, analyzing, and separately Anna --> killing) - we'll see "levels" of assemblage based on how many shared verbs they have I think.

**Comment by jilltxt** [comment]
@ragsol: 
> * Where is sentiment now? Hidden on both layers
We agreed sentiment should only be at the level of the work, so I will make it visible again there.

> * Is a corporation a "Thing" or a "Character"? Is a group a Character?
CHARACTERS: I think specific people or groups or entities are Characters. So a specific group where specific characteristics are meaningful (one or more of race, gender, age, species) is a character (e.g. if we wanted to add Circle Users they could be a Character (human, group). I will add individual/group to the Character entry.

OBJECT: A generic entity ("thing") (a corporation, a government, an image, a creator of a work) where we are not interested in details about race, age, gender.

Does that help?
