### ISSUE TITLE
What to do with situations that are pervasive rather than a specific event?

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#64]
Discuss: Should we create situations when machine vision is more than backdrop of a novel or similar rather than a specific event?

@LinnHeidi wrote: We have situations for when MV is used, but what about when MV is more the backdrop? It is a bit opposite to what we discussed with Jill`s situation from the Atwood book. No MV theme in the book, but has one MV situation. 

What if a story has a narrative where MV is often referred to casually and not in depth? It`s important to log it still. But should we have an alternative to situation? Situation to me is so "active" something is happening, and doing. But maybe there could be an option when MV is more of a backdrop? casual and passive. I have experienced especially by reading, but also when watching movies that there are contexts that are very machine visiony but does not feel enough to make a situation out of it?  I think maybe this can connect with also the "interactive" bit?

_Originally posted by @LinnHeidi in https://github.com/jilltxt/machinevision/issues/57#issuecomment-535470380_

**Comment by ragsol** [comment]
Do you have an example, @LinnHeidi ? It's kind of hard to say without something 'tangible' :) I think we said early on that there has to be a situation for us to log it, but I agree that there's something interesting with regards to interactivity and habitualization. Perhaps we have an extra document for those we didn't add to the database, but can reference in papers etc.?

**Comment by LinnHeidi** [comment]
A book that I´ve read has loads of smaller MV elements, but its not the main theme. It is often mentioned throughout the book (Robots are listening, Drones are watching, Mom playing VR because she is bored etc.)

I have tried to log some situations though:
https://machine-vision.no/content/our-life-forest

So the situations are minor, but in it is sort of the backdrop of the whole story (which seems important)

**Comment by ragsol** [comment]
Wow, that is tricky. I'm not sure I'd really count those as MV, but that's an interesting discussion!

**Comment by jilltxt** [comment]
Interesting question. I looked at the entries. Is this one machine vision, or just LISTENING surveillance? It's not clear from the description that there is visual surveillance going on?
https://machine-vision.no/content/robots-surveilling-conversation

And in this one there are robots and they see drones above them, but you've not tagged any machine vision technologies (except the general AI, which isn't really visual?)
https://machine-vision.no/content/our-life-forest

But then in the overall work you list several machine vision technologies. Hm. Maybe Ragnhild is right and we should have a more qualitative list of these rather than entering them in the database?

I kind of want to read this book though!

**Comment by LinnHeidi** [comment]
Good point Jill! I have not entered any obviously visual MV from this book! Where can I add this, if I am to remove it from the database?

You can grab the book, it is in the projectroom:)

**Comment by jilltxt** [comment]
Can you start a page in the Wiki, please, titled Works Not on Database Where Machine Vision is Pervasive? We can add works there?

**Comment by LinnHeidi** [comment]
Done. Then I will close this issue!
