### ISSUE TITLE
Add comments to Creative Works and Machine Vision Situations

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#66]
Update: Comments active on new entries. Need to add to existing entries. Looks like you have to change a setting in php to enable comments for all entries? https://www.drupal.org/forum/support/post-installation/2017-06-04/enable-comments-on-old-posts-of-a-content-type

Add comments to main node types. These should only be visible to Authenticated Users, and are just for project participants to discuss tagging of individual works.

Jill tried to do this like this:
1. Turned Comments on in [Modules](https://machine-vision.no/admin/modules)
2. In [Permissions](https://machine-vision.no/admin/people/permissions), I ticked Authenticated User
3. In the Manage Content Type for Situations I added Comments to the Display. 
<img width="805" alt="Screen Shot 2019-11-04 at 13 29 03" src="https://user-images.githubusercontent.com/44365847/68121084-2d37db00-ff07-11e9-845a-0329e525ed8a.png">
 4. In the Comment Display, I changed it from Hidden to Above.
<img width="796" alt="Screen Shot 2019-11-04 at 13 30 08" src="https://user-images.githubusercontent.com/44365847/68121122-42146e80-ff07-11e9-86c7-0189c4923bbb.png">

But the comments don't show up on any of the Situation nodes, so obviously I forgot something. Hoping Stein Magne can help when home from Chile.

**Comment by LinnHeidi** [comment]
You can comment when you have created a person

**Comment by jilltxt** [comment]
Seriously? That is extremely bizarre. I tried creating a new person but can't seem to add comments. Can you? Maybe I didn't give myself permission to add comments but somehow gave other users permission?

<img width="1066" alt="Screen Shot 2019-11-06 at 12 22 48" src="https://user-images.githubusercontent.com/44365847/68294366-41f3aa80-0090-11ea-97aa-62581ad29978.png">
https://machine-vision.no/person/test-test

**Comment by LinnHeidi** [comment]
Ah, no! Its no longer like that! Or maybe I saw the comment field somewhere else that was strange! But I like the comment sections!

**Comment by jilltxt** [comment]
Yes, I think comments would be really helpful for discussing tagging of specific works and situations. We can set this up when Stein Magne comes home.

**Comment by jilltxt** [comment]
Comments are visible on SOME entries. Here is an example:
https://machine-vision.no/content/ai-generated-nude-portraits-0#comment-2

**Comment by jilltxt** [comment]
I guess comments are showing on new entries. Looks like you have to change a setting in php to enable comments for all entries? https://www.drupal.org/forum/support/post-installation/2017-06-04/enable-comments-on-old-posts-of-a-content-type

**Comment by jilltxt** [comment]
Closing since this point will likely be moot with migration.
