### ISSUE TITLE
Situation Titles

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#67]
So we decided that Situations are:

Replicas (Will Deletes Zoe)

But what about tv-shows like Black Mirror? I have now done it so its:
Black Mirror: Striking Vipers (Karl and Danny has VR sex)

Is this okay?

**Comment by ragsol** [comment]
I think I'd just write "VR sex" tbh. Who does it is relevant when you click it..?

**Comment by LinnHeidi** [comment]
Okay, I am just using characters because that what we started doing at Solstrand: May killing Mercer etc.

But I have now renamed a bunch of situations to get a feel for it but they are all over the place, so it would be nice with some directions

**Comment by jilltxt** [comment]
Black Mirror: Striking Vipers (Brief description of situation) sounds good.
And I think I agree that the VR sex is probably enough. I don't think we really thought through using character names at Solstrand - is there something else we could call Mae killing Mercer? That isn't really a very descriptive title I guess. SoulSearch might be a better title for that one?

**Comment by LinnHeidi** [comment]
Yeah, but I kind of like it when it is very clear. Just having Soulsearch in the brackets seems a bit vague. 
Like with the situation: Replicas (Will deletes Zoe) it is so clear in few words what happens in this situation.

**Comment by jilltxt** [comment]
Yes. I don’t think it matters too much - try to keep the titles at four words or less, and character names are OK if needed for clarity.

**Comment by LinnHeidi** [comment]
Great, should we close this issue then?

**Comment by jilltxt** [comment]
Yes, I changed our instructions in the [wiki page for Situations]https://github.com/jilltxt/machinevision/wiki/Situation) and left a link to this discussion too. Closing :)
