### ISSUE TITLE
Insert link in Situation description

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#68]
The situation description has gone from being short to big, and sometimes it would be great to add text here too when it fits just right, but you cant insert links here for reference.

**Comment by jilltxt** [comment]
I changed the format of the field so you can switch between plain text and simple HTML when editing. Now you can use simple HTML tags like <a href="http://uib.no">this is a link to the UiB website</a>. Does that solve the issue?

**Comment by LinnHeidi** [comment]
Yes, thank you:)
