### ISSUE TITLE
Revise definitions of Technologies and Topics

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#70]
**TOPICS that needs to be discussed:**

Animals: BLANK

Biographical (REVISIT): Both autobiographical and biographical. Works narrating the experiences of an actual person, current, past or fictional.

Competition: Blank

Critical (REVISIT): BLANK

Dystopian (REVISIT): Set in or about an imagined state or society in which there is great suffering or injustice, typically one that is totalitarian or post-apocalyptic.

Economy (REVISIT): BLANK

Free will (REVISIT): The individual’s ability to make choices that aren’t predetermined or pre-programmed.

Gender (REVISIT): Explicitly addressing gender issues, e.g. gender (in)equality, gender identity or gender presentation. Does not works where gender is simply present without being problematised or presented as an important theme in the work itself. Highly sexualised appearance alone is about the protagonist, and should not be tagged in themes, unless it is clearly also a theme.

Hacking (REVISIT): Repurposing existing technology for purposes it was not originally intended for. Could also be the gaining of unauthorized access to technological systems and/or data is a key theme. Not necessarily illegal or framed as morally wrong or destructive.

Horror (REVISIT): Evoke fear, repulsion, disgust, terror and/or works that have elements of the grotesque, eerie, monstrous.

Intrusive: BLANK

Race (REVISIT): Explicitly addresses racial issues, e.g. racial (in)equality, racism, or identity as key themes. Does not necessarily involve skin colour. Art works dealing with physiognomy as racism and basis for discrimination may fit this tag. Also includes prejudice and discrimination against ethnic groups. Can include non-human or fictional groups, e.g. Captain Marvel, which presents racism again the Skrulls, or Binti, where a fictional African group of people are oppressed by other humans and by aliens. Brave New World would not qualify, though it would be tagged with “inequality” (though it doesn’t include machine vision).

Science Fiction: I guess Marianne will work on this

Speculative (REVISIT): Emphasis on what could have happened/what could happen, possible scenarios. Can include the improbable or the fairly realistic, and can be imaginative, contrafactual, or fantastic.

Utopian (REVISIT): Set in or about an imagined community or society that possesses highly desirable or nearly perfect qualities for its citizens.

**TECHNOLOGIES that needs to be discussed:**

Augmented reality (REVISIT): A technology that superimposes a computer-generated image on a user's view of the real world, thus providing a composite view (Wikipedia definition). Does not include the interface of a game that is visible to the player, but for technologies referenced, can include AR as experienced by an avatar in a game, if the avatar recognises the AR. AR is a technology used in Pokemon Go.

Body scans (REVISIT): Any imaging technology that shows parts of the body that are usually hidden, for instance brain imaging, fMRI, ultrasound, x-ray, or body scans in airport security that show objects under clothing. Includes cameras probes that enter the body. Does not include cameraphone apps for diagnosing melanomas, as the melanoma is not hidden but visible to the naked eye. Would include headbands for meditation that visualise brainwaves, as these are not normally visible.

Deepfake (REVISIT): Technologies that use machine learning to generate videos that strongly resemble a specific human being. For our purposes, we include for instance art, satire, spoofs, porn and revenge, but not professional uses of synthetic or virtual actors in Hollywood movies.

Image generation (REVISIT): Synthetic images generated using technologies such as GANs and other neural networks. Does not include animation in general.

I have just used the lists in the wiki, but please add if there is something else too.

**Comment by jilltxt** [comment]
Thanks for going through these, Linn Heidi!! We'll discuss on Tuesday :)

**Comment by jilltxt** [comment]
This is completed.
