### ISSUE TITLE
Part of the old Situations system visible on new page

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#71]
As of now, the "Machine vision technologies involved in this situation" is listed in the old system but also shows up in the Database. I haven't updated that bit because it's in the old part, but should we, or should it be hidden? It's in the verbs anyway, so might not be needed?

**Comment by jilltxt** [comment]
Let's discuss in meeting today.

**Comment by ragsol** [comment]
Removed from display, as decided in meeting Nov 18

**Comment by jilltxt** [comment]
Closing as will be fixed in migration.
