### ISSUE TITLE
Change naughty Generic Entities to Characters

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#76]
Please strike out items from this list when you have recreated them as Characters instead of  Generic Entities:

- [x] Aliens |  
- [x] Assimilation City |  
- [x] Bikers |  
- [x] Casino the Rapper |  
- [x] Chung`s archive |  
Corporation
Creator 
- [x] Crowd |  
- [x] Deer |  
- [x] Fans |  
- [x] Girls on screen |  
- [x] Glad Girls |  
Government
- [x] Humans --> Character |  
Image 
- [x] Images -> Image |  
- [x] Infant |  
- [x] Necklace --> Object | Add Object as Generic entity
- [x] Paper (band) |  
- [x] People --> |  
- [x] People approaching house |  
- [x] Person recording concert |  
- [x] Plastic surgeons |  
- [x] Police --> either mark as Government or create character |  
- [x] Population --> Humans (Character) |  
- [x] Robinator --> Character |  
- [x] Standing Rock Ground --> |  
- [x] Styled people --> Character |  
- [x] The Creator --> Creator |  
- [x] The Creator (Janelle) --> Creator |  
- [x] The Flemming Family --> Character |  
- [x] The Police Force --> either mark as Government or create character |  
- [x] The Workers --> Character |  
- [x] Tom --> Character |  
- [x] Unspecified individuals --> Humans (character, group) |  
User
- [x] Woman entering car --> make character – female human named: Woman? Or woman entering car |  
- [x] Women --> make character (group)

**Comment by LinnHeidi** [comment]
Chungs Archive is not a character - it is all the artworks of the artist Chung:https://machine-vision.no/content/drawing-operations-robot-collaborates-painting
So it is objects that the robot has been fed in order to learn.

**Comment by jilltxt** [comment]
I think we decided the archive should be a generic entity, but more generic. So either just “Images” or “Object”, whichever you think is more appropriate.

**Comment by LinnHeidi** [comment]
Standing Rock Ground --> |  I am not sure what this should be? It is an area. (From the documentary about the drone warriors Awake) https://machine-vision.no/content/awake-drones-documenting-oppression. Maybe have a generic entity for location?

**Comment by jilltxt** [comment]
Yes, we discussed having a Generic Entity called "Environment", since that is quite inclusive. Can you use that?

**Comment by jilltxt** [comment]
And wow, you have done a lot of these already! Awesome!
