### ISSUE TITLE
Amazon AWS EC2 micro instance stop working

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#78]
Got a sneaking suspicion that we are running out of server resources. Two system hangs in 3 weeks are not not supposed to happen. We reduced our AWS size to lower the hosting costs back in the autumn.

![Screen Shot 2020-01-27 at 16 31 31](https://user-images.githubusercontent.com/683617/73188012-87b98f80-4122-11ea-8f26-dc617a98f35b.png)

## Error noticed

`These checks monitor your software and network configuration for this instance.
Instance reachability check failed at January 26, 2020 at 5:31:00 AM UTC+1 (1 days, 10 hours and 43 minutes ago)`

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstances.html

## Suggested fix

* [x] Check logs and see if we are running out of memory on traffic spikes and getting killed by OOOM.
* [x] Change EC2 instance type allocating 2GB memory.
* [ ] Change and verify PHP-FPM and Apache workers match available memory.

**Comment by steinmb** [comment]
@jilltxt Verified that EC2 instance is running out of memory. I'll change from micro to something with more memory.

**Comment by jilltxt** [comment]
Ugh. Thanks for spotting this. I sent in the request for the UiB virtual server today.

**Comment by steinmb** [comment]
@jilltxt to change EC2 instance type I need to: shutdown, change, start, verify. About 10 minutes downtime.

**Comment by steinmb** [comment]
AWS instance type changed to `t3a.small` - doubling memory and CPU.

**Comment by jilltxt** [comment]
Thanks for doing this! Is it safe to close this issue do you think?

**Comment by steinmb** [comment]
No, leave it. Still one more task in the issue that is not finish.
