### ISSUE TITLE
 Machine Vision Situation Drupal 9 migration

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#84]
Migrate #61 node content from Drupal 7 to 8. Clean up data structure and omit not unused data and data structures.

## Data structures
Migrate all fields. All mapping is:`field_name: field_name` except if listed below.

Format: `D8: D7`

`field_record_status: field_record_status_tax`
`field_textfield: field_brief_description`
`field_multi_image: field_multi_images`

### Files and media assets:

```
Machine Vision Situation:
    Multimedia
        Field type: file
        Widget: Media browser
        Field: field_media_assetfield_media_asset
        Media types: Video, Image

    Screenshots or images
        Field type: image
        Widget: image
        Field: field_multi_images
        Media types: Image

```

## Needs work

* [x] Paragraphs: Who does what?  `field_actions`
    * [x] Bundle: Character Actions `character_actions`
    * [x] Bundle: Generic Entity Action (Thing) `generic_entity_action`
    * [x] Bundle: Technology Actions `technology_actions`
* [x] Files: `Screenshots or images` and `Multimedia`
* [x] Comments

## How to run test migration

`drush migrate:import uib_node_machine_vision_situation` and rollback nodes: `drush migrate:rollback uib_node_machine_vision_situation`

## How test

* Verify that fields contain correct values after migration.
* Verify that form and help text is correct looks OK. Do not have to look great but all data needs to be there.

**Comment by steinmb** [comment]
Mental note. Make sure these migrate correct if not update missing text format post-migration.

```
Processing machine_vision_situation
Illegal format. Node: 243 field_brief_description Format:
Illegal format. Node: 246 field_brief_description Format:
Illegal format. Node: 250 field_brief_description Format:
Illegal format. Node: 251 field_brief_description Format:
Illegal format. Node: 253 field_brief_description Format:
Illegal format. Node: 257 field_brief_description Format:
Illegal format. Node: 258 field_brief_description Format:
Illegal format. Node: 263 field_brief_description Format:
Illegal format. Node: 267 field_brief_description Format:
Illegal format. Node: 270 field_brief_description Format:
Illegal format. Node: 301 field_brief_description Format:
Illegal format. Node: 320 field_brief_description Format:
Illegal format. Node: 326 field_brief_description Format:
Illegal format. Node: 333 field_brief_description Format:
Illegal format. Node: 334 field_brief_description Format:
Illegal format. Node: 335 field_brief_description Format:
Illegal format. Node: 374 field_brief_description Format:
Illegal format. Node: 378 field_brief_description Format:
Illegal format. Node: 388 field_brief_description Format:
Illegal format. Node: 404 field_brief_description Format:
Illegal format. Node: 407 field_brief_description Format:
Illegal format. Node: 436 field_brief_description Format:
Illegal format. Node: 456 field_brief_description Format:
Illegal format. Node: 457 field_brief_description Format:
Illegal format. Node: 459 field_brief_description Format:
Illegal format. Node: 465 field_brief_description Format:
Illegal format. Node: 475 field_brief_description Format:
Illegal format. Node: 481 field_brief_description Format:
Illegal format. Node: 485 field_brief_description Format:
Illegal format. Node: 486 field_brief_description Format:
Illegal format. Node: 487 field_brief_description Format:
Illegal format. Node: 509 field_brief_description Format:
Illegal format. Node: 518 field_brief_description Format:
Illegal format. Node: 519 field_brief_description Format:
Illegal format. Node: 535 field_brief_description Format:
Illegal format. Node: 536 field_brief_description Format:
Illegal format. Node: 537 field_brief_description Format:
Illegal format. Node: 539 field_brief_description Format:
Illegal format. Node: 542 field_brief_description Format:
Illegal format. Node: 546 field_brief_description Format:
Illegal format. Node: 547 field_brief_description Format:
Illegal format. Node: 550 field_brief_description Format:
Illegal format. Node: 554 field_brief_description Format:
Illegal format. Node: 555 field_brief_description Format:
Illegal format. Node: 556 field_brief_description Format:
Illegal format. Node: 557 field_brief_description Format:
Illegal format. Node: 573 field_brief_description Format:
Illegal format. Node: 601 field_brief_description Format:
Illegal format. Node: 602 field_brief_description Format:
Illegal format. Node: 603 field_brief_description Format:
Illegal format. Node: 604 field_brief_description Format:
Illegal format. Node: 607 field_brief_description Format:
Illegal format. Node: 616 field_brief_description Format:
Illegal format. Node: 629 field_brief_description Format:
Illegal format. Node: 634 field_brief_description Format:
Illegal format. Node: 636 field_brief_description Format:
Illegal format. Node: 641 field_brief_description Format:
Illegal format. Node: 651 field_brief_description Format:
Illegal format. Node: 657 field_brief_description Format:
Illegal format. Node: 658 field_brief_description Format:
Illegal format. Node: 665 field_brief_description Format:
Illegal format. Node: 676 field_brief_description Format:
Illegal format. Node: 678 field_brief_description Format:
Illegal format. Node: 693 field_brief_description Format:
Illegal format. Node: 824 field_brief_description Format: 3
```

**Comment by steinmb** [comment]
Test migration and all basic data looked OK

![Screen Shot 2020-02-12 at 14 16 06](https://user-images.githubusercontent.com/683617/74338380-5982b380-4da2-11ea-8b64-d2310c98f336.png)

**Comment by jilltxt** [comment]
How is this looking, @steinmb?

**Comment by steinmb** [comment]
Re-testing migration. Found a problem with screenshots. Fixed in https://github.com/steinmb/uib_humanists/commit/b966c31af2bb32556823975bf177c6d68232cb95

**Comment by steinmb** [comment]
These two are not right. Checking in D9

![Screenshot 2020-06-11 at 17 16 21](https://user-images.githubusercontent.com/683617/84404582-5344fc80-ac07-11ea-9a0d-bb9be02cc9b9.png)

Though the data look to made it across (D7 vs D9). Different ID but that might not be crux.

![Screenshot 2020-06-11 at 17 20 33](https://user-images.githubusercontent.com/683617/84405115-057cc400-ac08-11ea-8dcc-1efe5806dcc9.png)

Going to look into it.

**Comment by steinmb** [comment]
Manually tested. The changed during migration though they are still the same:

```
Migrated data:

    "field_actions" => array:1 [▼
      "x-default" => array:3 [▼
        0 => array:2 [▼
          "target_id" => "1666"
          "target_revision_id" => "1666"
        ]
        1 => array:2 [▼
          "target_id" => "1176"
          "target_revision_id" => "1176"
        ]
        2 => array:2 [▼
          "target_id" => "1365"
          "target_revision_id" => "1365"
        ]
      ]
    ]

Manually edited:
   "field_actions" => array:1 [▼
      "x-default" => array:3 [▼
        0 => array:2 [▼
          "target_id" => "1666"
          "target_revision_id" => "1670"
        ]
        1 => array:2 [▼
          "target_id" => "1176"
          "target_revision_id" => "1671"
        ]
        2 => array:2 [▼
          "target_id" => "1365"
          "target_revision_id" => "1672"
        ]
      ]
    ]
```

Try to check dependencies.

commit a14d167d5d4d210859ec6cc77ae3e244a4478821 (HEAD -> master, origin/master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Jun 11 17:56:51 2020 +0200

    Revisions should only depend on main bundle

I think we should force Paragraphs to have dependencies on the taxonomy_group migration and node character migration.

**Comment by steinmb** [comment]
Retesting migration. Everything looks OK except the `UiB Paragraphs Technology Actions` migration. Did some detective work in the db.

```
SELECT * FROM paragraphs_item WHERE type = 'technology_actions';
......
301 rows in set
```
Meaning that the paragraph entities was migrated/created in D9.

```
SELECT * FROM paragraph__field_verbs WHERE bundle = 'technology_actions';
Empty set

MariaDB [mvisiond8]> SELECT * FROM paragraph__field_technology;
Empty set
```
This means that the entity field mapping did not work for some reason. I'll have a look later on today.

**Comment by steinmb** [comment]
Think I found it. Pushed a fix that need to be re-tested.

commit c0094ec6ad0b0e967f6a9739b1e920f82b5162e8 (HEAD -> master, origin/master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Jun 12 14:49:18 2020 +0200

    Technology Actions migration of tax terms did not work

    We use entity ref. field type but we still target taxonomy
    term and have to target it as term ref. not entity ref.

**Comment by steinmb** [comment]
Full migration test, again.

![Screenshot 2020-06-12 at 15 30 59](https://user-images.githubusercontent.com/683617/84507862-c14dfa00-acc1-11ea-9567-4a3afa0db6ca.png)

Found two related to machine vision situations that prevent me from closing this as fixed.

1. There seem to be a problem with order or revisions in paragraphs. Wrong values might be matched up.
1. Machine vision revisions do not contain paragraphs information. It might be just the migration that is not looking for old values.

**Comment by steinmb** [comment]
This addresses the revisions problem mention above:

commit 2b90cd748c9f7a0f5b4e588fb25e199c4d08a169 (HEAD -> master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Jun 12 15:42:03 2020 +0200

    No paragraphs info in machine vision situations revisions

**Comment by steinmb** [comment]
Late night tinkering. This change seems to do it. Migrate all content and retested. Looks OK

commit c3aab2d47e0731f37aa53437124a72e5624edd74 (HEAD -> master, origin/master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Jun 15 00:49:25 2020 +0200

    Machinevision situation paragraph use correct revision id

    Failed to use correct revision id. ID was always identical
    to target ID something that not aways is correct. Lead to
    wrong paragraph is used if found at all on node view/edit.

![Screenshot 2020-06-15 at 09 36 22](https://user-images.githubusercontent.com/683617/84630260-fb9adf80-aeeb-11ea-89ae-6fc193280c61.png)
