### ISSUE TITLE
Retag works marked as "speculative" and then delete speculative from taxonomy

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#85]
Can everyone please check "their" works here:
https://machine-vision.no/themes/speculative-mode
Skim "your" entries and check the checkbox by your name when you are OK with me deleting the tag completely.

- [x] Marianne
- [x] Jill
- [x] Linda
- [x] Ragnhild
- [x] Linn Heidi

When all have checked, Jill will delete.

**Comment by LinnHeidi** [comment]
I think I did all of mine, but browsing through some of the other entries I still find "Speculative". Maybe they are all @jilltxt entries, but I doubt it.

**Comment by jilltxt** [comment]
Deleted "Speculative".
