### ISSUE TITLE
Drupal 9 readiness

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#89]
A few things need to be done getting us ready for Drupal 9. Split out from task #61. We need to match: [Drupal 9 requirements](https://www.drupal.org/docs/understanding-drupal/how-drupal-9-is-made-and-what-is-included/environment-requirements-of).

## Sub tasks

* Register two subdomains. One to allow us to do a quick review before going in prod. An one to allow us to keep the old site around.
    * [x] Register domains - `old.machine-vision.no` and `new.machine-vision.no`
* [x] Create Drupal 9 empty database.
* [x] Install Drupal 7 module allowing us to put old site into read only mode.
* [x] Upgrade production PHP version in Amazon AWS cloud from 7.2.x to 7.3.x or 7.4.x.
* [x] Amazon AWS Linux 2 Composer version out of date. We should do a local installation to `/usr/local/bin` if no newer is available in prod.
* [x] VHOST settings and https cert. config

## Updated

```
php-cli.x86_64                  7.3.17-2.amzn2                @amzn2extra-php7.3
php-common.x86_64               7.3.17-2.amzn2                @amzn2extra-php7.3
php-fpm.x86_64                  7.3.17-2.amzn2                @amzn2extra-php7.3
php-gd.x86_64                   7.3.17-2.amzn2                @amzn2extra-php7.3
php-json.x86_64                 7.3.17-2.amzn2                @amzn2extra-php7.3
php-mbstring.x86_64             7.3.17-2.amzn2                @amzn2extra-php7.3
php-mysqlnd.x86_64              7.3.17-2.amzn2                @amzn2extra-php7.3
php-pdo.x86_64                  7.3.17-2.amzn2                @amzn2extra-php7.3
php-xml.x86_64                  7.3.17-2.amzn2                @amzn2extra-php7.3
```

**Comment by steinmb** [comment]
Before bumping I need to run a general update in prod. and a reboot. Calculate about 5 minutes downtime.

```
Transaction Summary
=====================================================================================================================================================================================
Install    6 Packages (+6 Dependent packages)
Upgrade  189 Packages

Total download size: 189 M
```

```
sudo amazon-linux-extras list | grep php
NOTE: The livepatch extra is in public preview, not meant for production use

 15  php7.2=latest            enabled      \
 17  lamp-mariadb10.2-php7.2  available    \
  _  php7.3                   available    \
  _  php7.4                   available    [ =stable ]
```

**Comment by jilltxt** [comment]
@steinmb, where should old.machine-vision.no and new.machine-vision point to? I think I found where I have to add them but think I have to say where to send people? 
<img width="992" alt="Screen Shot 2020-06-02 at 14 22 24" src="https://user-images.githubusercontent.com/44365847/83519623-9fdc5980-a4dc-11ea-8b26-ab8ba334dca8.png">

**Comment by steinmb** [comment]
@jilltxt - Send it to same place/address that `machine-vision.no` goes. It is the same server.

**Comment by steinmb** [comment]
Installed composer to /usr/local/bin
`Composer version 1.10.6 2020-05-06 10:28:10`

**Comment by jilltxt** [comment]
Then I think the domains are registered. It says it could take up to 90 mins.
<img width="909" alt="Screen Shot 2020-06-02 at 15 22 52" src="https://user-images.githubusercontent.com/44365847/83525292-0e251a00-a4e5-11ea-8010-f0597b636221.png">

**Comment by steinmb** [comment]
Thank you. I'll have a look then the change is propagated and synced

**Comment by steinmb** [comment]
@jilltxt Not sure what this registrar mean with "web forward". Ideally we register sub-domains as CNAME. Same way as `test.machinevision.no` was added. 

@jilltxt Update: Re-tested. Web forward is not right. We need a CNAME as mention above.

**Comment by jilltxt** [comment]
@steinmb I think I have added you as a guest user who can manage the domain's DNS settings - try that?

**Comment by steinmb** [comment]
Domain, Apache VHOST and SSL cert configured/generated. I think we are done in here.

https://new.machine-vision.no/test.html
https://old.machine-vision.no/test.html

**Comment by steinmb** [comment]
Should look into this:

```
CUSTOM PROJECTS
--------------------------------------------------------------------------------
Migrate Humanities
Scanned on Wed, 06/03/2020 - 13:27.

3 warnings found.

web/modules/uib_humanists/scripts/CleanUp.php:
┌──────────┬──────┬──────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                         MESSAGE                          │
├──────────┼──────┼──────────────────────────────────────────────────────────┤
│ Check    │      │ Class CleanUp was not found while trying to analyse it - │
│ manually │      │ autoloading is probably not configured properly.         │
│          │      │                                                          │
└──────────┴──────┴──────────────────────────────────────────────────────────┘

web/modules/uib_humanists/scripts/Location.php:
┌──────────┬──────┬─────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                         MESSAGE                         │
├──────────┼──────┼─────────────────────────────────────────────────────────┤
│ Check    │      │ Class Result was not found while trying to analyse it - │
│ manually │      │ autoloading is probably not configured properly.        │
│          │      │                                                         │
└──────────┴──────┴─────────────────────────────────────────────────────────┘

web/modules/uib_humanists/uib_humanists.info.yml:
┌──────────┬──────┬───────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                          │
├──────────┼──────┼───────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Add <code>core_version_requirement: ^8 || ^9</code> to    │
│ manually │      │ modules/uib_humanists/uib_humanists.info.yml to designate │
│          │      │ that the module is compatible with Drupal 9. See          │
│          │      │ https://drupal.org/node/3070687.                          │
│          │      │                                                           │
└──────────┴──────┴───────────────────────────────────────────────────────────┘
```

**Comment by steinmb** [comment]
Fix 

commit 743b2f3c915850721407740245e1c596b29a07cb (HEAD -> paragraphs, origin/paragraphs)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Jun 3 13:40:46 2020 +0200

    Make migration Drupal 9 compliant

**Comment by steinmb** [comment]
![Screen Shot 2020-06-03 at 13 54 47](https://user-images.githubusercontent.com/683617/83633830-d9c36380-a5a1-11ea-9a9e-dd7671c877f9.png)
