### ISSUE TITLE
Overview functionality

### ISSUE THREAD

**Issue by LinnHeidi** [jilltxt/machinevision#9]
I miss being able to scroll through all creative works. Currently on the dashboard it is only the latest ones. I can scroll through all of mine, but it would be great to be able to have a page with all the entries everyones has made.

**Comment by steinmb** [comment]
There is such a page on https://machinevision.elmcip.net/knowledgebase but currently is the link hard to spot. They lack proper position and visual weight.

![Screen Shot 2019-05-28 at 12 45 02](https://user-images.githubusercontent.com/683617/58472507-afe19080-8146-11e9-9492-b961172bc35a.png)

BUT, perhaps that is not the page you where talking about? Not 100% sure what you mean by `dashboard`. Is it your user page? found at https://machinevision.elmcip.net/user perhaps?

**Comment by jilltxt** [comment]
Fixed
