### ISSUE TITLE
Go through all old entries in database

### ISSUE THREAD

**Issue by ragsol** [jilltxt/machinevision#90]
I have my own list of all the entries I need to revisit or need help with, so I thought I could post it here and make this a task for everyone to go back to their listings and make sure they're tagged with _One person feels okay with this_ or list it here. That way, we'll help our future selves make sure the database is up to speed, and also, because we're not physically at the same place now, it makes it easier to help others with the listings they need to discuss :) Once the listing is clear, just remove it from your list.

An easy way to find your works is to go to [https://machine-vision.no/user](https://machine-vision.no/user). You can also go directly to the [drafts](https://machine-vision.no/record-status/draft) or [stubs](https://machine-vision.no/record-status/stub), but keep in mind that you might have some old entries that were cleared in a previous version of the database, so do check them all!

**Comment by ragsol** [comment]
**Revisits I need help with**
- Black Mirror (TV series)
- Love Death & Robots (TV series)
- Minority Report (film)
- The Circle (film)

**My revisits**
- Assassin's Creed IV: Black Flag (videogame)
- Call of Duty 4: Modern Warfare (videogame)
- Clandestine (videogame)
- Deus Ex: Human Revolution (videogame)
- Get Even (videogame)
- GTAV (videogame)
- Remember Me (videogame)
- Sleeping Dogs (videogame)
- State of Mind (videogame)
- Syndicate (videogame)
- Thief II: The Metal Age (videogame)
- Tom Clancy's Rainbow Six Siege (videogame)
- Whisper of a Machine (videogame)

**Comment by jilltxt** [comment]
Great! So you mean we should list entries here that are just stubs or drafts, for instance if they don't have the situations yet? Excellent idea.

**Comment by ragsol** [comment]
> 
> 
> Great! So you mean we should list entries here that are just stubs or drafts, for instance if they don't have the situations yet? Excellent idea.

Yeah - the list I have is all the ones that aren't tagged with "One person feels okay with this" that are created by my user. So I just list all the ones I know I/we have to revisit. Obviously, The Circle, Black Mirror, and Minority Report should be looked at by more people, but it's associated with my user, so I think it might be a pretty straight-forward way of making sure we go through everything :)

**Comment by ragsol** [comment]
Is done through personal lists and discord, not in use here.
