### ISSUE TITLE
Review migrated data in Drupal 8/9

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#94]
Naked migrated site https://new.machine-vision.no/ ready to check missing content, links, images, video etc. Please ignore layout and funky position of our data. Our job is just to make sure it is there and correct. User accounts are migrated and should work as expected.

## Known issues

1. Location (country) is not baked into the migration but are going to be added back after we have done the final migrating and replaced our current production site. In other words ignore that it is missing from persons. If interested you can track it's progress in issue #88.
1. Character sexuality field is missing - I am going to tackle that in issue #92
1. In Persons the two blocks listing works and contributed works are not there. Follow issue #93 for progress on that.

## How to test

* Check all the different content types we have. All data from the old site should be there.
* Verify that images, files and videos are there.
* Taxonomy terms are also migrated and should be checked.
* Verify that content revisions are there and contain information and not empty.

**Comment by steinmb** [comment]
Stuff that might stump you, permissions. The new site have only so fare been tested by root/admin/sudo/user1/Odin, an user that where permissions are not validated. I have migrated all the old user groups to the new site. These groups did we inherited from ELMCIP and I feel that they do not fit us at all and I would like to drop all of them all except the admin group that Jill and my personal account uses. The remaining users should all have same access.

**Comment by jilltxt** [comment]
This looks great! I logged in as "Jill" and didn't see any problems. There are some things not really to do with the data itself, like the links in the intro text on https://new.machine-vision.no/knowledgebase go to the old URLs, but that's easily fixed (or maybe fixes itself when the URL is changed). The list of entries belonging to a specific technology, like here https://new.machine-vision.no/knowledgebase doesn't need full entries, could just be a list of titles (maybe with genre) but that's not a big deal to fix later. Otherwise I didn't see any problems.

**Comment by jilltxt** [comment]
Back links from an Creator to works the creator created aren't there. But that's not about the data, that's about making views and stuff.

**Comment by steinmb** [comment]
> Back links from an Creator to works the creator created aren't there. But that's not about the data, that's about making views and stuff.

I think that is known issue number 3, right?

**Comment by jilltxt** [comment]
Oh, that's what that issue meant. Thanks :)

**Comment by LindaKairus** [comment]
So if we are just to check if all content is there I did not find anything missing so far. However, non of the links are working. I can only go back to the list of works. If I click on Type, Tech, Sentiment etc. links then I just get to the newest work added, not the list. But I am not sure if this was something we should comment on yet.

**Comment by steinmb** [comment]
>So if we are just to check if all content is there I did not find anything missing so far. However, non of the links are working. I can only go back to the list of works. If I click on Type, Tech, Sentiment etc. links then I just get to the newest work added, not the list. But I am not sure if this was something we should comment on yet.

Thanks for the feedback. The link in the knowledgebase block work, it is just us listing the content differently. The way it was you got a looong list of articles tagged with that term if you just kept scrolling. Like this:

![Screenshot_2020-06-16 AI Machine Vision](https://user-images.githubusercontent.com/683617/84786877-9b8c6200-afed-11ea-90a0-75e6db7a8412.jpg)

**Comment by steinmb** [comment]
@LindaKairus Not very practical, I know :) I have changed it to something that is similar to how the old installation do it. Example: https://new.machine-vision.no/taxonomy/term/168

**Comment by steinmb** [comment]
Hooked up the live Drupal 7 database in production and checked our content.

![Screenshot 2020-06-17 at 10 46 24](https://user-images.githubusercontent.com/683617/84886935-5facd780-b095-11ea-8cd5-6234bf8e1dfb.png)

A little drift in data. That is normal. Last night though I put Drupal 7 version in read only mode so these are data that changed before that.

**Comment by steinmb** [comment]
Since we also had changed/new files I had to map up the Drupal storage area. Did an update of the data types that had changed.

## Result

```
 --------------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
  Group                             Migration ID                                       Status   Total   Imported   Unprocessed   Last Imported
 --------------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
  UiB content (uib_nodes)           uib_node_character                                 Idle     305     305        0             2020-06-17 08:43:53
  UiB content (uib_nodes)           uib_node_revision_character                        Idle     62      62         0             2020-06-17 08:43:53
  UiB content (uib_nodes)           uib_node_machine_vision_situation                  Idle     320     320        0             2020-06-17 08:43:58
  UiB content (uib_nodes)           uib_node_person                                    Idle     274     274        0             2020-06-17 08:44:01
  UiB content (uib_nodes)           uib_node_work                                      Idle     250     250        0             2020-06-17 08:44:09
  UiB content (uib_nodes)           uib_node_revision_machine_vision_situation         Idle     779     779        0             2020-06-17 08:44:21
  UiB content (uib_nodes)           uib_node_revision_person                           Idle     53      53         0             2020-06-17 08:44:22
  UiB content (uib_nodes)           uib_node_revision_work                             Idle     1162    1162       0             2020-06-17 08:44:54

  UiB files (uib_files)             uib_file                                           Idle     602     602        0             2020-06-17 08:54:26
  UiB files (uib_files)             uib_vimeo_video                                    Idle     37      37         0             2020-06-14 22:57:21
  UiB files (uib_files)             uib_youtube_video                                  Idle     101     101        0             2020-06-14 22:57:34
  UiB files (uib_files)             uib_image                                          Idle     602     602        0             2020-06-17 08:56:26

  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_creative_work_publication_type   Idle     21      21         0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_gender                           Idle     5       5          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_race                             Idle     9       9          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_record_status                    Idle     5       5          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_species                          Idle     5       5          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_age                              Idle     4       4          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_colours                          Idle     31      31         0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_generic_entities                 Idle     55      55         0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_individual_or_group              Idle     2       2          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_sentiment                        Idle     20      20         0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_sexuality                        Idle     4       4          0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_technologies                     Idle     27      27         0             2020-06-14 22:57:42
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_themes                           Idle     36      36         0             2020-06-14 22:57:43
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_verbs                            Idle     667     667        0             2020-06-17 08:43:23
  UiB taxonomy (uib_taxonomy)       uib_taxonomy_term_visual_characteristics           Idle     274     274        0             2020-06-14 22:57:48

  UiB Users (uib_users)             uib_user_role                                      Idle     10      10         0             2020-06-14 22:57:05
  UiB Users (uib_users)             uib_user                                           Idle     10      10         0             2020-06-14 22:57:05

  UiB paragraphs (uib_paragraphs)   uib_paragraphs_character_actions                   Idle     343     343        0             2020-06-17 08:42:19
  UiB paragraphs (uib_paragraphs)   uib_paragraphs_generic_entity_action               Idle     190     190        0             2020-06-17 08:42:20
  UiB paragraphs (uib_paragraphs)   uib_paragraphs_technology_actions                  Idle     302     302        0             2020-06-17 08:42:21
 --------------------------------- -------------------------------------------------- -------- ------- ---------- ------------- ---------------------
```

**Comment by steinmb** [comment]
We are done
