### ISSUE TITLE
Install Search API facilitating generic search and faceting 

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#96]
In the Drupal 7 site (https://old.machine-vision.no/search/node) we used Drupal core search. In Drupal 9 the plan is to use Search API and it's faceting filters giving us powerful ways of drilling and filtering the content. It also give the ability to use the search engine creating custom views lists and so on.

# Scope of work

* [x] Install search API module and configure basic search backend and search index
* [x] few example facet filters.
* ~~[ ] Theme and layout adjustment to search field.~~

# How to test

Go to: https://machine-vision.no/search and do your worst

**Comment by steinmb** [comment]
@jilltxt Search API installed. Excellent baseline to build more powerful search and filtering than out the box Drupal core search. Search is a ongoing process req, tuning, changes as we go. https://machine-vision.no/search

![Screenshot 2020-06-24 at 11 38 49](https://user-images.githubusercontent.com/683617/85531838-66949680-b60f-11ea-96af-4f1aa9b8a72f.png)

Created a very basic search. Searching all nodes, not optimization have been done. Except:

* Case insensitive
* Stemmer enabled - https://en.wikipedia.org/wiki/Stemming
* Simple CJK handling - https://en.wikipedia.org/wiki/CJK_characters

We now can create search lists of "everything" using views with all the bells and whistles. Current we only have one index, containing node content.

The view is found: https://machine-vision.no/admin/structure/views/view/search

**Comment by jilltxt** [comment]
Look good! Thanks!
