### ISSUE TITLE
Configure and set up content alias pattern and redirects

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#97]
We should set up path aliases for the new site. 

## Patterns

* Media
* Content: `[node:content-type]/[node:title]`
* Taxonomy term: `[term:vocabulary]/[term:name]`
* User: `user/[user:display-name]`

## Changing alias

Use an redirect that automatic generate an redirect to new alias making sure we do not brake old url. We should return a 301 (permanently moved) to client (user/browser/robot).

## Original report

@ragsol wrote:
>Also, not sure if it goes here, but from the Knowledgebase's introduction (https://machine-vision.no/knowledgebase) the publication types don't work (e.g. "game", https://machine-vision.no/creative-work-publication-type/game). Funky enough, "topics" work. Further down, "game" works, but leads here: https://machine-vision.no/taxonomy/term/3 - so I guess it's just about the links in the introductory text.

**Comment by steinmb** [comment]
We currently only have two alias in use:
![Screenshot 2020-07-13 at 12 16 52](https://user-images.githubusercontent.com/683617/87307911-b41f6780-c51a-11ea-8b9c-f7c0288ab90b.png)

We should also configure a redirect that take care of - What happen when the alias change. And change they to. Example would be from the original rapport from @ragsol about game. 

The alias was from `term 3` to `creative-work-publication-type/game` The is is created out of the `vocabulary name/term title`. If you rename the title, let's say to `games` the alias change to `creative-work-publication-type/games`

**Comment by steinmb** [comment]
To start us of I have created a pattern for terms and generated 1165 URL aliases out of the one we have.

**Comment by steinmb** [comment]
Added and generated these:

`[node:content-type]/[node:title]` - Nodes,  `generated 1150 URL aliases`
`user/[user:display-name]`

**Comment by ragsol** [comment]
Not sure if this goes here, but anyway:
Is it possible to go into e.g. "games" from the main page and be able to click "title" to get them alphabetically sorted? Here's [page 1 ](https://machine-vision.no/creative-work-publication-type/game)of currently 5, and they're sorted based on what I assume is the most recent update? It's no worries if it's a tricky fix, but I had to jump back and forth between tabs a bit to update my own forms with the database titles :)

**Comment by steinmb** [comment]
>Not sure if this goes here, but anyway:

101% unrelated to this 😺  though I enabled that you click title to sort asc/desc. The default sort is by `post date`. If there is more follow ups on this pls. create a separate issue to avoid clutter in carefully planned and scoped issues 😉

**Comment by steinmb** [comment]
Decided not create 'media` path alias. I do not think we need it. No feedback, consider issue fixed. Closing.
