### ISSUE TITLE
Two split 33/67% or 50/50% layout is easily broken by oversized content elements

### ISSUE THREAD

**Issue by steinmb** [jilltxt/machinevision#98]
Example: https://machine-vision.no/node/1239

## Config

![Screenshot 2020-07-13 at 15 49 47](https://user-images.githubusercontent.com/683617/87312228-8e955c80-c520-11ea-9069-8118dd361cbd.png)

## Result

![Screenshot_2020-07-13 AI The Somnium Files Machine Vision](https://user-images.githubusercontent.com/683617/87312073-6279db80-c520-11ea-86f6-eb9036da1b4a.png)

**Comment by steinmb** [comment]
Updated to lates version of the base theme. There is a constant shift in baseline code but some good came out of it. Changes have been done preventing larger/longer content element from breaking the layout.

**Comment by jilltxt** [comment]
@steinmb, what needs review? Is it kind of fixed now?

**Comment by steinmb** [comment]
It might be. I have not had time to click through and look at the different content. If you find the time. If it looks OK, just go ahead and close the issue.

**Comment by steinmb** [comment]
Consider this OK. Major issue seems to have been addressed. Closing.
