### ISSUE TITLE
Free tags in aesthetics etc all turned into controlled vocabularies 

### ISSUE THREAD

**Issue by jilltxt** [jilltxt/machinevision#99]
Make form elements behave as expected. Some vocabularies should be controlled and some open so new entries.

### Machine vision situations

Free tagging and allowed to create new

* Aesthetic characteristics
* Colours

## Character

* Gender - Free tagging but not allowed to create new.
* Sexuality - Free tagging and allowed to create new
* Race/ethnicity - Free tagging but not allowed to create new.
* Species - Free tagging but not allowed to create new.
* Age - Free tagging but not allowed to create new.

## How to test

Create new/edit existing character and machine vision situations and make sure the form element listed above works as expected.

**Comment by steinmb** [comment]
Lets see if we get them right this time around. These have been changed to `autocomplete tag style`

## Machine vision situations

* Aesthetic characteristics
* Colours

## Character

* Gender
* Sexuality
* Race/ethnicity
* Species
* Age

**Comment by mareinna** [comment]
Character tags should all use the established controlled vocabulary, so I think they were fine as they were!.

In situations, the boxes that should be free tagged are the Aesthetic characteristics and Colours, which you fixed, but it looks like you missed the verbs that we add to the Technology/Character/Entity (the "this Character/Technology/Entity is:" boxes.

**Comment by steinmb** [comment]
>Character tags should all use the established controlled vocabulary, so I think they were fine as they were!.

That is fine, I can revert that change. I was simply mirroring the old site setup since the orignal post contained non details what what changes we are trying to pull off.

**Comment by steinmb** [comment]
>In situations, the boxes that should be free tagged are the Aesthetic characteristics and Colours, which you fixed, but it looks like you missed the verbs that we add to the Technology/Character/Entity (the "this Character/Technology/Entity is:" boxes.

Not sure I follow you. This is how `field_verbs` configured:

![Screenshot 2020-09-01 at 13 52 33](https://user-images.githubusercontent.com/683617/91846362-760d0d00-ec5a-11ea-8c37-aaceb4cea0f9.png)

Could you provide screenshot of the form you are ref. to?

**Comment by jilltxt** [comment]
@mareinna - can you take a look at this when you get a chance?

**Comment by jilltxt** [comment]
Sorry this took a while. The issue is still a problem, here is what it looks like. It's not the verbs, it's the Aesthetic characteristics.

<img width="627" alt="Screen Shot 2020-09-21 at 10 52 18" src="https://user-images.githubusercontent.com/44365847/93748644-e2938000-fbf8-11ea-9cda-6d5672e3d4e1.png">

**Comment by steinmb** [comment]
That is fine. I have done the change and the issue can be retested. I also updated the OP (original post) with a list of the changes in this issue.

I might have involuntary done changes to [Characters form](https://machine-vision.no/admin/content?title=&type=character&status=All&langcode=All) that I should not. Would love to get some feedback on them.

**Comment by steinmb** [comment]
Updated the top post again trying to make the issue clearer 👍

**Comment by jilltxt** [comment]
Closing this as it's no longer relevant now that we aren't doing data entry anymore.
